const xlsx = require('xlsx');
const path = require('path');

const data = [
  ["Word", "Clue 1", "Clue 2", "Clue 3", "Clue 4", "Clue 5", "Category", "Difficulty"],
  
  // Legends
  ["Pele", "Legend", "10 Number", "World Cup", "Brazil", "Santos", "Legends", "Easy"],
  ["Diego Maradona", "Hand of God", "Napoli", "10 Number", "Argentina", "Legend", "Legends", "Easy"],
  ["Johan Cruyff", "Total Football", "Ajax", "Legend", "Netherlands", "Barcelona", "Legends", "Medium"],
  ["Zinedine Zidane", "Headbutt", "Juventus", "Real Madrid", "France", "Legend", "Legends", "Easy"],
  ["Ronaldinho", "Smile", "Skill", "Milan", "Brazil", "Barcelona", "Legends", "Easy"],
  ["Ronaldo Nazario", "Injuries", "Inter", "Real Madrid", "Brazil", "Barcelona", "Legends", "Medium"],
  ["Thierry Henry", "Forward", "Placé", "France", "Barcelona", "Arsenal", "Legends", "Medium"],
  ["Paolo Maldini", "Captain", "Defender", "Legend", "Italy", "Milan", "Legends", "Medium"],
  ["Roberto Carlos", "Free Kick", "Left Back", "Real Madrid", "Fenerbahce", "Brazil", "Legends", "Medium"],
  ["George Best", "Dribbling", "7 Number", "Legend", "Northern Ireland", "Manchester United", "Legends", "Hard"],
  ["Ferenc Puskas", "Award", "Forward", "Left Foot", "Hungary", "Real Madrid", "Legends", "Hard"],
  ["Alfredo Di Stefano", "Legend", "Argentina", "Spain", "Champions League", "Real Madrid", "Legends", "Hard"],
  ["Eusebio", "Forward", "Portugal", "Black Panther", "Legend", "Benfica", "Legends", "Hard"],
  ["Gerd Muller", "Striker", "Der Bomber", "Goalscorer", "Germany", "Bayern Munich", "Legends", "Medium"],
  ["Franz Beckenbauer", "Der Kaiser", "Libero", "Legend", "Germany", "Bayern Munich", "Legends", "Medium"],
  ["Lev Yashin", "Black Spider", "Ballon dOr", "Dynamo Moscow", "Soviet Union", "Goalkeeper", "Legends", "Hard"],
  ["Bobby Charlton", "Midfielder", "World Cup", "Legend", "England", "Manchester United", "Legends", "Hard"],
  ["Marco van Basten", "Volley", "Forward", "Legend", "Netherlands", "Milan", "Legends", "Medium"],
  ["Ruud Gullit", "Dreadlocks", "PSV", "Feyenoord", "Netherlands", "Milan", "Legends", "Hard"],
  ["Frank Rijkaard", "Spit", "Midfielder", "Netherlands", "Galatasaray", "Milan", "Legends", "Hard"],
  ["Franco Baresi", "Captain", "Defender", "Legend", "Italy", "Milan", "Legends", "Hard"],
  ["Roberto Baggio", "Divine Ponytail", "Penalty", "Juventus", "Italy", "Legend", "Legends", "Medium"],
  ["Lothar Matthaus", "World Cup", "Midfielder", "Inter", "Germany", "Bayern Munich", "Legends", "Hard"],
  ["Oliver Kahn", "Aggressive", "Der Titan", "Goalkeeper", "Germany", "Bayern Munich", "Legends", "Medium"],
  ["Peter Schmeichel", "Saves", "Legend", "Goalkeeper", "Denmark", "Manchester United", "Legends", "Medium"],
  ["Eric Cantona", "Kung-Fu", "Collars", "The King", "France", "Manchester United", "Legends", "Medium"],
  ["Dennis Bergkamp", "Fear of Flying", "Dribbling", "Forward", "Netherlands", "Arsenal", "Legends", "Medium"],
  ["Clarence Seedorf", "Muscles", "Champions League", "Real Madrid", "Netherlands", "Milan", "Legends", "Hard"],
  ["Pavel Nedved", "Hair", "Ballon dOr", "Midfielder", "Czech Republic", "Juventus", "Legends", "Hard"],
  ["Rivaldo", "Bicycle Kick", "Olympiacos", "Left Foot", "Brazil", "Barcelona", "Legends", "Medium"],
  ["Luis Figo", "Pig Head", "Traitor", "Portugal", "Real Madrid", "Barcelona", "Legends", "Medium"],
  ["David Beckham", "Free Kick", "Spice Boy", "Real Madrid", "England", "Manchester United", "Legends", "Easy"],
  ["Ryan Giggs", "Left Midfield", "Welsh", "Legend", "Wales", "Manchester United", "Legends", "Medium"],
  ["Paul Scholes", "Passing", "Ginger", "Midfielder", "England", "Manchester United", "Legends", "Medium"],
  ["Steven Gerrard", "Slip", "Captain", "Midfielder", "England", "Liverpool", "Legends", "Medium"],
  ["Frank Lampard", "Manager", "Midfielder", "Chelsea", "England", "Legend", "Legends", "Medium"],
  ["Wayne Rooney", "Everton", "Striker", "Wazza", "England", "Manchester United", "Legends", "Easy"],
  ["Didier Drogba", "Galatasaray", "Champions League", "Striker", "Ivory Coast", "Chelsea", "Legends", "Easy"],
  ["Samuel Eto'o", "Antalyaspor", "Striker", "Inter", "Cameroon", "Barcelona", "Legends", "Medium"],
  ["Carles Puyol", "Hair", "Defender", "Captain", "Spain", "Barcelona", "Legends", "Medium"],
  ["Iker Casillas", "Heart Attack", "Porto", "Goalkeeper", "Spain", "Real Madrid", "Legends", "Medium"],
  ["Gianluigi Buffon", "Parma", "PSG", "Goalkeeper", "Italy", "Juventus", "Legends", "Easy"],
  ["Andrea Pirlo", "Free Kick", "Maestro", "Midfielder", "Italy", "Juventus", "Legends", "Medium"],
  ["Francesco Totti", "Loyalty", "Captain", "Gladiator", "Italy", "Roma", "Legends", "Medium"],
  ["Alessandro Del Piero", "Captain", "Forward", "Legend", "Italy", "Juventus", "Legends", "Medium"],
  ["Javier Zanetti", "Tractor", "Captain", "Defender", "Argentina", "Inter", "Legends", "Hard"],
  ["Rio Ferdinand", "Leeds", "Defender", "Pundit", "England", "Manchester United", "Legends", "Medium"],
  ["Nemanja Vidic", "Spartak Moscow", "Defender", "Captain", "Serbia", "Manchester United", "Legends", "Hard"],
  ["John Terry", "Captain", "Defender", "Slip", "England", "Chelsea", "Legends", "Medium"],
  ["Ashley Cole", "Left Back", "Arsenal", "Roma", "England", "Chelsea", "Legends", "Medium"],
  ["Petr Cech", "Helmet", "Arsenal", "Goalkeeper", "Czech Republic", "Chelsea", "Legends", "Medium"],
  ["Patrick Vieira", "Captain", "Midfielder", "Juventus", "France", "Arsenal", "Legends", "Hard"],
  ["Roy Keane", "Aggressive", "Captain", "Midfielder", "Ireland", "Manchester United", "Legends", "Medium"],
  ["Bastian Schweinsteiger", "Chicago Fire", "Midfielder", "World Cup", "Germany", "Bayern Munich", "Legends", "Hard"],
  ["Philipp Lahm", "Captain", "Right Back", "World Cup", "Germany", "Bayern Munich", "Legends", "Medium"],
  ["Arjen Robben", "Cut Inside", "Left Foot", "Chelsea", "Netherlands", "Bayern Munich", "Legends", "Easy"],
  ["Franck Ribery", "Scar", "Winger", "Galatasaray", "France", "Bayern Munich", "Legends", "Medium"],
  ["Wesley Sneijder", "Inter", "Midfielder", "Netherlands", "Real Madrid", "Galatasaray", "Legends", "Easy"],
  ["Robin van Persie", "Flying Dutchman", "Fenerbahce", "Arsenal", "Netherlands", "Manchester United", "Legends", "Medium"],
  ["Gareth Bale", "Golf", "Wales", "Tottenham", "Speed", "Real Madrid", "Legends", "Easy"],
  ["Eden Hazard", "Injuries", "Winger", "Belgium", "Real Madrid", "Chelsea", "Legends", "Easy"],
  ["Sergio Aguero", "Heart", "93:20", "Striker", "Argentina", "Manchester City", "Legends", "Medium"],
  ["Vincent Kompany", "Manager", "Captain", "Defender", "Belgium", "Manchester City", "Legends", "Medium"],
  ["David Silva", "El Mago", "Midfielder", "Spain", "Real Sociedad", "Manchester City", "Legends", "Medium"],
  ["Yaya Toure", "Birthday Cake", "Midfielder", "Ivory Coast", "Barcelona", "Manchester City", "Legends", "Hard"],

  // Active Stars
  ["Lionel Messi", "World Cup", "Inter Miami", "Left Foot", "Argentina", "Barcelona", "Players", "Easy"],
  ["Cristiano Ronaldo", "Al Nassr", "7 Number", "Portugal", "Real Madrid", "Juventus", "Players", "Easy"],
  ["Andres Iniesta", "Vissel Kobe", "Midfielder", "World Cup", "Spain", "Barcelona", "Players", "Medium"],
  ["Xavi Hernandez", "Manager", "Tiki Taka", "Midfielder", "Spain", "Barcelona", "Players", "Medium"],
  ["Luka Modric", "Ballon dOr", "Midfielder", "Tottenham", "Croatia", "Real Madrid", "Players", "Easy"],
  ["Toni Kroos", "Sniper", "Midfielder", "Passing", "Germany", "Real Madrid", "Players", "Easy"],
  ["Karim Benzema", "Al Ittihad", "Ballon dOr", "Striker", "France", "Real Madrid", "Players", "Easy"],
  ["Robert Lewandowski", "Dortmund", "Striker", "Poland", "Bayern Munich", "Barcelona", "Players", "Easy"],
  ["Neymar", "Al Hilal", "Skills", "Brazil", "PSG", "Barcelona", "Players", "Easy"],
  ["Kylian Mbappe", "Speed", "World Cup", "France", "PSG", "Real Madrid", "Players", "Easy"],
  ["Erling Haaland", "Robot", "Striker", "Dortmund", "Norway", "Manchester City", "Players", "Easy"],
  ["Kevin De Bruyne", "Assist", "Midfielder", "Wolfsburg", "Belgium", "Manchester City", "Players", "Easy"],
  ["Mohamed Salah", "Pharaoh", "Left Foot", "Roma", "Egypt", "Liverpool", "Players", "Easy"],
  ["Sadio Mane", "Al Nassr", "Winger", "Bayern Munich", "Senegal", "Liverpool", "Players", "Medium"],
  ["Virgil van Dijk", "Captain", "Defender", "Southampton", "Netherlands", "Liverpool", "Players", "Medium"],
  ["Alisson Becker", "Header Goal", "Roma", "Goalkeeper", "Brazil", "Liverpool", "Players", "Medium"],
  ["Trent Alexander-Arnold", "Free Kick", "Right Back", "Cross", "England", "Liverpool", "Players", "Medium"],
  ["Andrew Robertson", "Left Back", "Hull City", "Scotland", "Assist", "Liverpool", "Players", "Hard"],
  ["Harry Kane", "Striker", "England", "Bayern Munich", "Trophyless", "Tottenham", "Players", "Easy"],
  ["Heung-min Son", "Winger", "Captain", "Bayer Leverkusen", "South Korea", "Tottenham", "Players", "Medium"],
  ["Jude Bellingham", "Golden Boy", "Dortmund", "Midfielder", "England", "Real Madrid", "Players", "Easy"],
  ["Vinicius Junior", "Winger", "Speed", "Flamengo", "Brazil", "Real Madrid", "Players", "Easy"],
  ["Rodrygo", "Winger", "Santos", "Champions League", "Brazil", "Real Madrid", "Players", "Medium"],
  ["Federico Valverde", "Energy", "Midfielder", "Uruguay", "Peñarol", "Real Madrid", "Players", "Medium"],
  ["Thibaut Courtois", "Tall", "Atletico Madrid", "Goalkeeper", "Belgium", "Real Madrid", "Players", "Medium"],
  ["Antonio Rudiger", "Aggressive", "Defender", "Chelsea", "Germany", "Real Madrid", "Players", "Medium"],
  ["David Alaba", "Chair", "Defender", "Austria", "Bayern Munich", "Real Madrid", "Players", "Medium"],
  ["Pedri", "Golden Boy", "Las Palmas", "Midfielder", "Spain", "Barcelona", "Players", "Medium"],
  ["Gavi", "Aggressive", "Midfielder", "La Masia", "Spain", "Barcelona", "Players", "Medium"],
  ["Lamine Yamal", "Record", "Winger", "Teenager", "Spain", "Barcelona", "Players", "Easy"],
  ["Marc-Andre ter Stegen", "Hair Transplant", "Goalkeeper", "Gladbach", "Germany", "Barcelona", "Players", "Medium"],
  ["Frenkie de Jong", "Ajax", "Midfielder", "Dribbling", "Netherlands", "Barcelona", "Players", "Medium"],
  ["Ronald Araujo", "Defender", "Pace", "Uruguay", "Header", "Barcelona", "Players", "Medium"],
  ["Antoine Griezmann", "Hair", "Left Foot", "Atletico Madrid", "France", "Barcelona", "Players", "Medium"],
  ["Ousmane Dembele", "Injuries", "Two Footed", "Dortmund", "France", "PSG", "Players", "Medium"],
  ["Gianluigi Donnarumma", "Tall", "AC Milan", "Goalkeeper", "Italy", "PSG", "Players", "Medium"],
  ["Marquinhos", "Captain", "Defender", "Roma", "Brazil", "PSG", "Players", "Medium"],
  ["Achraf Hakimi", "Right Back", "Inter", "Morocco", "Real Madrid", "PSG", "Players", "Medium"],
  ["Jamal Musiala", "Dribbling", "Midfielder", "Bambi", "Germany", "Bayern Munich", "Players", "Medium"],
  ["Florian Wirtz", "Assist", "Midfielder", "Bayer Leverkusen", "Germany", "Champion", "Players", "Medium"],
  ["Joshua Kimmich", "Right Back", "Midfielder", "Stuttgart", "Germany", "Bayern Munich", "Players", "Medium"],
  ["Thomas Muller", "Raumdeuter", "Assist", "Funny", "Germany", "Bayern Munich", "Players", "Medium"],
  ["Manuel Neuer", "Sweeper Keeper", "Schalke", "Goalkeeper", "Germany", "Bayern Munich", "Players", "Easy"],
  ["Alphonso Davies", "Speed", "Left Back", "Vancouver", "Canada", "Bayern Munich", "Players", "Medium"],
  ["Leroy Sane", "Left Foot", "Winger", "Manchester City", "Germany", "Bayern Munich", "Players", "Medium"],
  ["Phil Foden", "Stockport", "Midfielder", "Left Foot", "England", "Manchester City", "Players", "Medium"],
  ["Bernardo Silva", "Left Foot", "Monaco", "Midfielder", "Portugal", "Manchester City", "Players", "Medium"],
  ["Ruben Dias", "Leader", "Defender", "Benfica", "Portugal", "Manchester City", "Players", "Medium"],
  ["Rodri", "Defensive Midfield", "Atletico Madrid", "Goal", "Spain", "Manchester City", "Players", "Easy"],
  ["Ederson", "Tattoos", "Passing", "Goalkeeper", "Brazil", "Manchester City", "Players", "Medium"],
  ["Kyle Walker", "Speed", "Right Back", "Tottenham", "England", "Manchester City", "Players", "Medium"],
  ["Martin Odegaard", "Captain", "Real Madrid", "Midfielder", "Norway", "Arsenal", "Players", "Medium"],
  ["Bukayo Saka", "Starboy", "Winger", "Left Foot", "England", "Arsenal", "Players", "Easy"],
  ["Declan Rice", "West Ham", "Defensive Midfield", "Expensive", "England", "Arsenal", "Players", "Medium"],
  ["William Saliba", "Defender", "Saint-Etienne", "France", "Marseille", "Arsenal", "Players", "Hard"],
  ["Gabriel Martinelli", "Speed", "Winger", "Brazil", "Ituano", "Arsenal", "Players", "Hard"],
  ["Bruno Fernandes", "Complaining", "Penalty", "Sporting", "Portugal", "Manchester United", "Players", "Medium"],
  ["Marcus Rashford", "Charity", "Winger", "Speed", "England", "Manchester United", "Players", "Medium"],
  ["Casemiro", "Defensive Midfield", "Real Madrid", "Brazil", "Porto", "Manchester United", "Players", "Medium"],
  ["Alejandro Garnacho", "Bicycle Kick", "Winger", "Argentina", "Atletico Madrid", "Manchester United", "Players", "Hard"],
  ["Cole Palmer", "Cold", "Left Foot", "Manchester City", "England", "Chelsea", "Players", "Medium"],
  ["Enzo Fernandez", "World Cup", "River Plate", "Midfielder", "Argentina", "Chelsea", "Players", "Medium"],
  ["Rafael Leao", "Speed", "Winger", "Sporting", "Portugal", "AC Milan", "Players", "Medium"],
  ["Theo Hernandez", "Speed", "Left Back", "Real Madrid", "France", "AC Milan", "Players", "Medium"],
  ["Lautaro Martinez", "El Toro", "Striker", "Racing", "Argentina", "Inter", "Players", "Medium"],
  ["Nicolo Barella", "Energy", "Midfielder", "Cagliari", "Italy", "Inter", "Players", "Hard"],
  ["Khvicha Kvaratskhelia", "Kvaradona", "Winger", "Dribbling", "Georgia", "Napoli", "Players", "Medium"],
  ["Victor Osimhen", "Mask", "Striker", "Lille", "Nigeria", "Napoli", "Players", "Medium"],
  ["Dusan Vlahovic", "Left Foot", "Striker", "Fiorentina", "Serbia", "Juventus", "Players", "Medium"],
  ["Federico Chiesa", "Injuries", "Winger", "Fiorentina", "Italy", "Juventus", "Players", "Medium"]
];

const filePath = path.join("C:\\\\Users\\\\ysfde\\\\OneDrive\\\\Desktop", 'football_en.xlsx');
const ws = xlsx.utils.aoa_to_sheet(data);
const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Football");

try {
  xlsx.writeFile(wb, filePath);
  console.log('Successfully created! Total rows: ' + data.length);
} catch (e) {
  console.error(e);
}
