const xlsx = require('xlsx');
const path = require('path');

const data = [
  ['Word', 'Hint 1 (Hard)', 'Hint 2', 'Hint 3', 'Hint 4', 'Hint 5 (Easy)', 'Category', 'Difficulty'],
  ["Michael Jackson", "Started in a family band from Gary, Indiana", "Popularized the robot dance style", "His 1982 album is the best-selling of all time", "Signature white glove and fedora", "King of Pop / Moonwalk", "Pop", "Easy"],
  ["The Beatles", "Started playing in clubs in Hamburg, Germany", "Their final studio album was Let It Be", "Band members included a drummer named Ringo", "Wrote 'Hey Jude' and 'Yesterday'", "Legendary 4-piece rock band from Liverpool", "Rock", "Easy"],
  ["Queen", "Originally formed by Brian May and Roger Taylor as 'Smile'", "Recorded the soundtrack for the film Flash Gordon", "Their 1985 Live Aid performance is legendary", "Hits include 'We Will Rock You'", "Led by frontman Freddie Mercury", "Rock", "Easy"],
  ["Madonna", "Moved to NY with $35 to pursue modern dance", "Starred in the film Evita", "Hits include 'Vogue' and 'Material Girl'", "Known for reinventing her image", "The Queen of Pop", "Pop", "Easy"],
  ["Elvis Presley", "Started his career at Sun Records in Memphis", "Served in the US Army in Germany", "His home is called Graceland", "Hits include 'Hound Dog' and 'Jailhouse Rock'", "The King of Rock and Roll", "Rock", "Easy"],
  ["Taylor Swift", "Her family owned a Christmas tree farm", "Switched from country to pop with her 1989 album", "Known for writing songs about her exes", "Fans are called 'Swifties'", "Currently running 'The Eras Tour'", "Pop", "Easy"],
  ["Beyoncé", "Her alter ego was named Sasha Fierce", "Starred in the movie Dreamgirls", "Started in the group Destiny's Child", "Hits include 'Single Ladies' and 'Halo'", "Known as 'Queen Bey' and married to Jay-Z", "Pop/R&B", "Easy"],
  ["Eminem", "Starred in the movie 8 Mile", "His alter ego is Slim Shady", "Hits include 'Stan' and 'Without Me'", "Won an Oscar for 'Lose Yourself'", "Famous white rapper from Detroit", "Hip Hop", "Easy"],
  ["Lady Gaga", "Attended NYU's Tisch School of the Arts", "Starred in A Star Is Born alongside Bradley Cooper", "Wore a dress made of raw meat to the MTV VMAs", "Hits include 'Bad Romance' and 'Poker Face'", "Fans are called 'Little Monsters'", "Pop", "Easy"],
  ["Adele", "Attended the BRIT School in London", "Recorded the theme song for the James Bond film Skyfall", "Her albums are named after her age (19, 21, 25, 30)", "Known for the hit 'Rolling in the Deep'", "Famous British powerhouse vocalist", "Pop", "Easy"],
  ["Nirvana", "Their first album was 'Bleach'", "Played a legendary MTV Unplugged concert in 1993", "Pioneered the Seattle grunge sound", "Hits include 'Come As You Are'", "Fronted by the late Kurt Cobain", "Rock", "Medium"],
  ["Pink Floyd", "Early years were led by Syd Barrett", "Known for elaborate live shows and concept albums", "Created the rock opera 'The Wall'", "Hits include 'Comfortably Numb'", "Their album 'The Dark Side of the Moon' has a prism cover", "Rock", "Medium"],
  ["Led Zeppelin", "Formed from the ashes of The Yardbirds", "Their fourth album has no title, just four symbols", "Guitarist is Jimmy Page", "Known for the epic 'Stairway to Heaven'", "Legendary 70s hard rock band", "Rock", "Medium"],
  ["Rolling Stones", "Named after a Muddy Waters song", "Their logo is a famous red tongue and lips", "Hits include 'Paint It Black'", "Guitarist is Keith Richards", "Fronted by Mick Jagger", "Rock", "Easy"],
  ["David Bowie", "His first hit was released days before the Apollo 11 moon landing", "Acted as Jareth the Goblin King in 'Labyrinth'", "Created the alter ego Ziggy Stardust", "Hits include 'Space Oddity' and 'Heroes'", "Legendary chameleon of rock", "Rock", "Medium"],
  ["Prince", "Wrote 'Nothing Compares 2 U' for Sinead O'Connor", "Changed his name to an unpronounceable symbol", "Associated with the Minneapolis sound", "Hits include 'When Doves Cry' and 'Kiss'", "Famous for the album and movie 'Purple Rain'", "Pop/Funk", "Easy"],
  ["Whitney Houston", "Started out singing in a New Jersey gospel choir", "Starred in the movie The Bodyguard", "Known for an incredible 5-octave vocal range", "Hits include 'I Wanna Dance with Somebody'", "Famous for singing 'I Will Always Love You'", "Pop/R&B", "Easy"],
  ["Elton John", "His real name is Reginald Kenneth Dwight", "Collaborated for decades with lyricist Bernie Taupin", "Knights by Queen Elizabeth II", "Hits include 'Rocket Man' and 'Tiny Dancer'", "Famous British singer who plays the piano in extravagant outfits", "Pop/Rock", "Easy"],
  ["Bob Dylan", "Born Robert Allen Zimmerman", "Won the Nobel Prize in Literature in 2016", "Pioneered the folk-rock movement", "Hits include 'Blowin' in the Wind'", "Legendary folk singer with a distinct, raspy voice", "Folk/Rock", "Hard"],
  ["Bruce Springsteen", "His backing band is the E Street Band", "Often writes about working-class life in New Jersey", "Nicknamed 'The Boss'", "Hits include 'Dancing in the Dark'", "Famous for the album 'Born in the U.S.A.'", "Rock", "Medium"],
  ["AC/DC", "Formed by Scottish-born brothers Malcolm and Angus Young", "Their lead singer Bon Scott died in 1980", "Angus Young wears a schoolboy uniform on stage", "Hits include 'Thunderstruck' and 'Highway to Hell'", "Legendary Australian hard rock band", "Rock", "Easy"],
  ["Metallica", "Formed in Los Angeles in 1981 by Lars Ulrich and James Hetfield", "Their 1986 album 'Master of Puppets' is a genre classic", "Pioneers of thrash metal", "Hits include 'Enter Sandman' and 'Nothing Else Matters'", "The most commercially successful heavy metal band", "Metal", "Medium"],
  ["Guns N' Roses", "Their debut album 'Appetite for Destruction' is the best-selling debut in US history", "Features guitarist Slash and his top hat", "Hits include 'Welcome to the Jungle'", "Hits include 'November Rain'", "Fronted by Axl Rose", "Rock", "Easy"],
  ["Coldplay", "Met at University College London", "Their debut album was 'Parachutes' in 2000", "Known for the hit 'Yellow'", "Hits include 'Viva La Vida' and 'Fix You'", "Fronted by Chris Martin", "Rock/Pop", "Easy"],
  ["U2", "Formed in Dublin, Ireland in 1976", "Guitarist is known as The Edge", "Famous for the album 'The Joshua Tree'", "Hits include 'With or Without You'", "Fronted by Bono", "Rock", "Medium"],
  ["Red Hot Chili Peppers", "Originally formed under the name Tony Flow and the Miraculously Majestic Masters of Mayhem", "Flea is their famous bassist", "Their breakthrough album was 'Blood Sugar Sex Magik'", "Hits include 'Under the Bridge' and 'Californication'", "California funk-rock band", "Rock", "Medium"],
  ["Linkin Park", "Their debut album 'Hybrid Theory' is one of the best-selling of the 21st century", "Blended nu-metal with rap and electronica", "DJ Joe Hahn directed many of their videos", "Hits include 'In the End' and 'Numb'", "Co-fronted by the late Chester Bennington and Mike Shinoda", "Rock", "Easy"],
  ["Green Day", "Their 1994 album 'Dookie' revived interest in punk rock", "Created a Broadway musical based on one of their albums", "Hits include 'Basket Case' and 'Wake Me Up When September Ends'", "Hits include 'Boulevard of Broken Dreams'", "Fronted by Billie Joe Armstrong", "Rock", "Easy"],
  ["Radiohead", "Their debut single 'Creep' was initially a commercial failure", "Released the groundbreaking album 'OK Computer'", "Known for their experimental and electronic rock sound", "Hits include 'Karma Police' and 'No Surprises'", "Fronted by Thom Yorke", "Rock", "Hard"],
  ["The Cure", "Formed in Crawley, West Sussex in 1978", "Known for their gothic rock sound and aesthetic", "Hits include 'Just Like Heaven' and 'Friday I\\'m in Love'", "Hits include 'Boys Don\\'t Cry'", "Fronted by Robert Smith and his messy hair/lipstick", "Rock", "Hard"],
  ["Fleetwood Mac", "Started as a British blues band before becoming pop-rock giants", "Their album 'Rumours' was recorded amidst massive intra-band relationship drama", "Features members Stevie Nicks and Lindsey Buckingham", "Hits include 'Dreams' and 'Go Your Own Way'", "Hits include 'The Chain'", "Rock", "Medium"],
  ["The Eagles", "Started as Linda Ronstadt's backing band", "Their 'Greatest Hits (1971–1975)' is one of the best-selling albums ever", "Drummer Don Henley is one of the lead vocalists", "Hits include 'Take It Easy' and 'Desperado'", "Famous for the song 'Hotel California'", "Rock", "Medium"],
  ["Aerosmith", "Formed in Boston in 1970", "Collaborated with Run-DMC on a groundbreaking rap-rock crossover", "Known as the 'Bad Boys from Boston'", "Hits include 'Dream On' and 'I Don\\'t Want to Miss a Thing'", "Fronted by Steven Tyler", "Rock", "Medium"],
  ["Bon Jovi", "Formed in New Jersey in 1983", "Their album 'Slippery When Wet' was a massive success", "Guitarist Richie Sambora was a key member", "Hits include 'You Give Love a Bad Name'", "Famous for the anthem 'Livin\\' on a Prayer'", "Rock", "Easy"],
  ["Pearl Jam", "Formed in Seattle after the demise of Mother Love Bone", "Their debut album was 'Ten'", "Fought against Ticketmaster in the 90s", "Hits include 'Alive' and 'Jeremy'", "Fronted by Eddie Vedder", "Rock", "Medium"],
  ["Foo Fighters", "Started as a one-man project after the end of Nirvana", "Their first album was recorded entirely by one person", "Hits include 'Everlong' and 'The Pretender'", "Hits include 'Best of You' and 'Learn to Fly'", "Fronted by Dave Grohl", "Rock", "Easy"],
  ["Muse", "Formed in Teignmouth, Devon in 1994", "Known for their classical-infused alternative rock and space themes", "Hits include 'Knights of Cydonia' and 'Starlight'", "Hits include 'Uprising' and 'Supermassive Black Hole'", "Fronted by Matt Bellamy", "Rock", "Medium"],
  ["Arctic Monkeys", "One of the first bands to come to public attention via the internet (MySpace)", "Their debut album is the fastest-selling in UK chart history", "Hits include 'I Bet You Look Good on the Dancefloor'", "Hits include '505' and 'R U Mine?'", "Known for the album 'AM' and the hit 'Do I Wanna Know?'", "Rock", "Medium"],
  ["The Killers", "Formed in Las Vegas in 2001", "Their debut album 'Hot Fuss' brought them international success", "Hits include 'Somebody Told Me' and 'When You Were Young'", "Fronted by Brandon Flowers", "Famous for the anthem 'Mr. Brightside'", "Rock", "Medium"],
  ["Imagine Dragons", "Formed in Las Vegas, Nevada", "Won a Grammy for Best Rock Performance for 'Radioactive'", "Known for blending pop, rock, and electronic elements", "Hits include 'Demons' and 'Thunder'", "Famous for the hit 'Believer'", "Rock/Pop", "Easy"],
  // Pop additions
  ["Justin Bieber", "Discovered by Scooter Braun via YouTube covers", "His 3D concert film 'Never Say Never' was a huge hit", "Had a highly publicized on-and-off relationship with Selena Gomez", "Hits include 'Sorry' and 'Love Yourself'", "Canadian pop star famous for the song 'Baby'", "Pop", "Easy"],
  ["Ed Sheeran", "Slept on Jamie Foxx's couch early in his career", "Uses a loop pedal extensively in live performances", "His albums are named after mathematical symbols (+, x, ÷, =, -)", "Hits include 'Thinking Out Loud' and 'Perfect'", "Famous British singer with red hair who sang 'Shape of You'", "Pop", "Easy"],
  ["Ariana Grande", "Started acting on the Nickelodeon shows Victorious and Sam & Cat", "Known for her whistle register and four-octave vocal range", "Her signature look includes a high ponytail", "Hits include 'Thank U, Next' and '7 Rings'", "Famous pop star who sings 'Dangerous Woman' and 'No Tears Left to Cry'", "Pop", "Easy"],
  ["Bruno Mars", "Born Peter Gene Hernandez in Hawaii", "Known for his retro showmanship and performing with his band, The Hooligans", "Performed at the Super Bowl halftime show twice", "Hits include '24K Magic' and 'Just the Way You Are'", "Famous for 'Uptown Funk'", "Pop/R&B", "Easy"],
  ["Katy Perry", "Released a gospel album early in her career under her real name", "Performed at the Super Bowl halftime show with 'Left Shark'", "Known for colorful, theatrical music videos", "Hits include 'Firework' and 'Roar'", "Famous for the song 'I Kissed a Girl'", "Pop", "Easy"],
  ["Rihanna", "Born in Saint Michael, Barbados", "Founded the cosmetics brand Fenty Beauty", "Starred in the movie Ocean's 8", "Hits include 'Diamonds' and 'We Found Love'", "Famous for the song 'Umbrella'", "Pop/R&B", "Easy"],
  ["Miley Cyrus", "Her godmother is Dolly Parton", "Her 2013 performance at the VMAs was highly controversial", "Hits include 'Party in the U.S.A.' and 'Flowers'", "Famous for swinging on a 'Wrecking Ball'", "Starred as Hannah Montana on Disney Channel", "Pop", "Easy"],
  ["Selena Gomez", "Started her career on Barney & Friends", "Starred in the Disney Channel series Wizards of Waverly Place", "Executive produced the Netflix series 13 Reasons Why", "Hits include 'Lose You to Love Me' and 'Hands to Myself'", "Stars in 'Only Murders in the Building'", "Pop", "Easy"],
  ["Shawn Mendes", "Gained a following on the video-sharing app Vine", "Canadian singer who often plays acoustic guitar", "Dated Camila Cabello", "Hits include 'Stitches' and 'Treat You Better'", "Famous for the song 'Senorita'", "Pop", "Medium"],
  ["Dua Lipa", "Her name means 'love' in Albanian", "Started her career by posting covers on YouTube", "Won the Grammy for Best New Artist in 2019", "Hits include 'Levitating' and 'New Rules'", "Famous for the song 'Don't Start Now'", "Pop", "Easy"],
  ["Billie Eilish", "Writes and produces music with her brother Finneas", "Recorded the theme song for the James Bond film No Time to Die", "Known for her whispered vocals and baggy clothing", "Hits include 'Therefore I Am' and 'Ocean Eyes'", "Famous for the song 'Bad Guy'", "Pop", "Easy"],
  ["Harry Styles", "Auditioned for The X Factor as a solo candidate before joining a group", "Starred in the movies Dunkirk and Don't Worry Darling", "Known for his flamboyant fashion sense", "Hits include 'Watermelon Sugar' and 'As It Was'", "Former member of One Direction", "Pop", "Easy"],
  ["The Weeknd", "Born Abel Makkonen Tesfaye in Toronto", "Performed at the Super Bowl LV halftime show", "Known for his dark, moody R&B and 80s synth-pop sound", "Hits include 'The Hills' and 'Starboy'", "Famous for the song 'Blinding Lights'", "Pop/R&B", "Easy"],
  ["Post Malone", "His stage name was generated using a rap name generator", "Known for his many facial tattoos", "Blends hip hop, pop, R&B, and country", "Hits include 'Circles' and 'Congratulations'", "Famous for the song 'Rockstar'", "Hip Hop/Pop", "Medium"],
  ["Drake", "Played Jimmy Brooks on the teen drama Degrassi", "Co-founded the OVO Sound record label", "Has the most charted songs in Billboard Hot 100 history", "Hits include 'Hotline Bling' and 'God\\'s Plan'", "Famous Canadian rapper", "Hip Hop", "Easy"],
  ["Kendrick Lamar", "Won a Pulitzer Prize for Music for his album 'DAMN.'", "Curated the soundtrack for the Marvel film Black Panther", "Known for his socially conscious lyrics", "Hits include 'HUMBLE.' and 'Alright'", "Famous rapper from Compton, California", "Hip Hop", "Medium"],
  ["Kanye West", "Started as a producer for Roc-A-Fella Records", "His debut album was 'The College Dropout'", "Founded the Yeezy fashion brand", "Hits include 'Stronger' and 'Gold Digger'", "Famous Chicago rapper known for his controversies", "Hip Hop", "Easy"],
  ["Jay-Z", "Former CEO of Def Jam Recordings", "First hip-hop artist to become a billionaire", "Hits include '99 Problems' and 'Empire State of Mind'", "Married to Beyonce", "Legendary Brooklyn rapper and founder of Roc Nation", "Hip Hop", "Easy"],
  ["Snoop Dogg", "Discovered by Dr. Dre and featured on 'The Chronic'", "His debut album was 'Doggystyle'", "Changed his name to 'Snoop Lion' for a reggae album", "Hits include 'Gin and Juice'", "Famous West Coast rapper who says 'Drop It Like It\\'s Hot'", "Hip Hop", "Easy"],
  ["Tupac Shakur", "Studied acting and poetry at the Baltimore School for the Arts", "His alter ego was Makaveli", "Starred in the movies Juice and Poetic Justice", "Hits include 'Dear Mama' and 'Changes'", "Legendary West Coast rapper famous for 'California Love'", "Hip Hop", "Easy"],
  ["The Notorious B.I.G.", "Also known as Biggie Smalls", "His debut album was 'Ready to Die'", "Key figure in the East Coast hip hop scene", "Hits include 'Juicy' and 'Big Poppa'", "Legendary Brooklyn rapper who was killed in 1997", "Hip Hop", "Medium"],
  ["Nicki Minaj", "Known for her colorful wigs and rapid-fire rap style", "Her fans are called 'Barbz'", "Hits include 'Super Bass' and 'Starships'", "Famous for her verse on Kanye West's 'Monster'", "Female rapper from Trinidad and Tobago", "Hip Hop", "Easy"],
  ["Cardi B", "Gained fame on Vine and Instagram before joining Love & Hip Hop", "Her debut album won the Grammy for Best Rap Album", "Hits include 'I Like It' and 'WAP'", "Married to rapper Offset", "Famous female rapper known for 'Bodak Yellow'", "Hip Hop", "Easy"],
  ["Travis Scott", "Organizes the Astroworld Festival", "Collaborated with McDonald's on a signature meal", "Known for his highly energetic live shows", "Hits include 'Goosebumps' and 'Highest in the Room'", "Famous rapper known for 'Sicko Mode'", "Hip Hop", "Medium"],
  ["J. Cole", "First artist signed to Jay-Z's Roc Nation label", "Known for going platinum with no features", "His albums include '2014 Forest Hills Drive'", "Hits include 'No Role Modelz' and 'Middle Child'", "Famous rapper raised in North Carolina", "Hip Hop", "Medium"],
  // R&B/Soul
  ["Stevie Wonder", "Signed with Motown Records at age 11 as a child prodigy", "Pioneered the use of synthesizers in R&B", "Hits include 'Sir Duke' and 'Isn\\'t She Lovely'", "Famous for the song 'Superstition'", "Legendary blind singer and keyboardist", "Soul/R&B", "Medium"],
  ["Marvin Gaye", "Helped shape the sound of Motown in the 1960s", "His concept album 'What's Going On' is considered a masterpiece", "Hits include 'Let's Get It On' and 'Sexual Healing'", "Famous for 'I Heard It Through the Grapevine'", "Legendary soul singer known as the Prince of Motown", "Soul", "Medium"],
  ["Aretha Franklin", "Started singing at the New Bethel Baptist Church in Detroit", "First female artist inducted into the Rock and Roll Hall of Fame", "Hits include 'Think' and 'A Natural Woman'", "Famous for the song 'Respect'", "Legendary singer known as the Queen of Soul", "Soul", "Easy"],
  ["Ray Charles", "Pioneered soul music by combining blues, gospel, and R&B", "Lost his sight at age 7 due to glaucoma", "Played by Jamie Foxx in a 2004 biopic", "Hits include 'Georgia on My Mind' and 'Hit the Road Jack'", "Legendary blind singer and pianist known as 'The Genius'", "Soul/R&B", "Medium"],
  ["James Brown", "Known for his energetic stage performances and dancing", "Often sampled in hip hop music", "Hits include 'Papa's Got a Brand New Bag'", "Famous for 'Get Up (I Feel Like Being a) Sex Machine'", "Legendary singer known as the Godfather of Soul", "Soul/Funk", "Medium"],
  ["Tina Turner", "Started her career performing with her abusive husband Ike", "Her comeback album 'Private Dancer' was a massive success", "Known for her energetic stage presence and powerful vocals", "Hits include 'What's Love Got to Do with It'", "Legendary singer known as the Queen of Rock 'n' Roll", "Rock/Soul", "Medium"],
  ["Alicia Keys", "A classically trained pianist who started composing at age 12", "Her debut album 'Songs in A Minor' won five Grammys", "Served as a coach on The Voice", "Hits include 'Fallin'' and 'No One'", "Famous for singing 'Empire State of Mind' with Jay-Z", "R&B", "Easy"],
  ["John Legend", "First black man to achieve EGOT status", "His real last name is Stephens", "Played a role in the movie La La Land", "Married to Chrissy Teigen", "Famous for the song 'All of Me'", "R&B/Pop", "Easy"],
  ["Usher", "Discovered Justin Bieber and helped launch his career", "His album 'Confessions' is one of the best-selling of the 2000s", "Performed at the Super Bowl LVIII halftime show", "Hits include 'U Got It Bad' and 'Burn'", "Famous for the song 'Yeah!'", "R&B", "Easy"],
  // Jazz
  ["Louis Armstrong", "Grew up in New Orleans and learned to play in a reform school", "Known for his inventive trumpet playing and scat singing", "His nickname was 'Satchmo'", "Hits include 'Hello, Dolly!'", "Legendary jazz musician famous for 'What a Wonderful World'", "Jazz", "Easy"],
  ["Frank Sinatra", "Started his career in the swing era with Harry James and Tommy Dorsey", "Was a founding member of the Rat Pack", "Nicknamed 'Ol\\' Blue Eyes'", "Hits include 'My Way' and 'Fly Me to the Moon'", "Legendary crooner famous for 'New York, New York'", "Jazz/Traditional Pop", "Easy"],
  ["Miles Davis", "His album 'Kind of Blue' is the best-selling jazz album of all time", "Constantly reinvented his style, pioneering cool jazz and jazz fusion", "Known for his muted trumpet sound", "His albums include 'Bitches Brew'", "Legendary and influential jazz trumpet player", "Jazz", "Hard"],
  ["Ella Fitzgerald", "Discovered at an amateur night at the Apollo Theater", "Known for her pure tone, impeccable diction, and improvisational ability", "Her nickname was the 'First Lady of Song'", "Famous for her 'scat' singing", "Legendary jazz vocalist known as the Queen of Jazz", "Jazz", "Medium"],
  ["Duke Ellington", "Led his jazz orchestra from 1923 until his death", "A prominent figure in the Harlem Renaissance", "Wrote over 1,000 compositions", "Hits include 'Take the A Train' and 'It Don\\'t Mean a Thing'", "Legendary jazz pianist and big band leader", "Jazz", "Medium"],
  ["Billie Holiday", "Had a difficult childhood and began singing in Harlem nightclubs", "Her autobiography was made into the film 'Lady Sings the Blues'", "Known for her emotive delivery and improvisation skills", "Her nickname was 'Lady Day'", "Legendary jazz singer famous for 'Strange Fruit'", "Jazz", "Hard"],
  ["Nina Simone", "Originally aspired to be a classical pianist", "Her music was highly influential during the Civil Rights Movement", "Hits include 'Feeling Good' and 'Sinnerman'", "Famous for the song 'I Put a Spell on You'", "Legendary jazz, blues, and folk singer", "Jazz/Blues", "Medium"],
  // Classical
  ["Wolfgang Amadeus Mozart", "Born in Salzburg, Austria", "Composed his first piece of music at age 5", "Wrote over 600 works before dying at age 35", "His works include 'The Magic Flute' and 'Requiem'", "Legendary Classical era child prodigy composer", "Classical", "Easy"],
  ["Ludwig van Beethoven", "Born in Bonn, Germany", "A crucial figure in the transition between the Classical and Romantic eras", "Composed some of his most important works after losing his hearing", "His works include 'Symphony No. 9' and 'Für Elise'", "Legendary deaf composer", "Classical", "Easy"],
  ["Johann Sebastian Bach", "Had 20 children, several of whom also became composers", "A German composer of the Baroque period", "Known for his mastery of counterpoint and fugue", "His works include the 'Brandenburg Concertos'", "Legendary composer of 'Toccata and Fugue in D minor'", "Classical", "Medium"],
  ["Frederic Chopin", "Born in Poland but spent most of his life in Paris", "Had a highly publicized relationship with the writer George Sand", "Wrote almost exclusively for the solo piano", "His works include the 'Minute Waltz' and various Nocturnes", "Legendary Romantic era piano virtuoso", "Classical", "Medium"],
  ["Pyotr Ilyich Tchaikovsky", "A Russian composer of the Romantic period", "His music is known for its strong melodies and emotional appeal", "His works include the '1812 Overture'", "Famous for composing the ballets 'Swan Lake' and 'The Nutcracker'", "Legendary Russian composer", "Classical", "Easy"],
  ["Antonio Vivaldi", "An Italian Baroque composer and virtuoso violinist", "Was an ordained Catholic priest nicknamed 'The Red Priest'", "Worked at an orphanage for girls in Venice", "His works include 'Gloria'", "Legendary composer of 'The Four Seasons'", "Classical", "Medium"],
  ["Claude Debussy", "A French composer who rejected traditional musical forms", "Often associated with Impressionist music, though he disliked the term", "His works include 'La Mer'", "Famous for the piano piece 'Clair de lune'", "Legendary French composer", "Classical", "Hard"],
  ["George Frideric Handel", "Born in Germany but spent most of his career in London", "A Baroque composer known for his operas and oratorios", "His works include 'Water Music' and 'Music for the Royal Fireworks'", "Famous for the 'Hallelujah Chorus'", "Legendary composer of 'Messiah'", "Classical", "Hard"],
  // Electronic/Dance
  ["Daft Punk", "Formed in Paris in 1993", "Provided the score for the film Tron: Legacy", "Rarely showed their real faces in public", "Hits include 'Get Lucky' and 'One More Time'", "Legendary French electronic duo known for their robot helmets", "Electronic", "Easy"],
  ["Avicii", "Born Tim Bergling in Stockholm, Sweden", "Retired from touring in 2016 due to health issues and tragically died in 2018", "Blended electronic music with elements of country and bluegrass", "Hits include 'Levels' and 'Hey Brother'", "Legendary Swedish DJ famous for 'Wake Me Up'", "Electronic", "Medium"],
  ["David Guetta", "Started as a DJ at nightclubs in Paris", "Helped popularize EDM globally in the late 2000s and early 2010s", "Collaborated frequently with Sia and Nicki Minaj", "Hits include 'Titanium' and 'Without You'", "Famous French DJ and record producer", "Electronic", "Medium"],
  ["Calvin Harris", "Born Adam Richard Wiles in Scotland", "Topped Forbes' list of highest-paid DJs for several consecutive years", "Dated Taylor Swift", "Hits include 'Summer' and 'This Is What You Came For'", "Famous Scottish DJ and producer", "Electronic", "Medium"],
  ["Skrillex", "Former lead singer of the post-hardcore band From First to Last", "Won eight Grammy Awards, more than any other EDM artist", "Formed the duo Jack Ü with Diplo", "Pioneered the popularization of dubstep in the US", "Famous DJ known for 'Bangarang'", "Electronic", "Medium"],
  ["The Chainsmokers", "An American electronic DJ and production duo", "Their song 'Closer' tied the record for most weeks in the top 10 of the Billboard Hot 100", "Members are Alexander 'Alex' Pall and Andrew 'Drew' Taggart", "Hits include 'Don\\'t Let Me Down' and 'Roses'", "Famous DJ duo known for 'Something Just Like This'", "Electronic", "Medium"],
  // Reggae/Latin/World
  ["Bob Marley", "Born in Nine Mile, Jamaica", "Survived an assassination attempt in 1976", "A committed Rastafari whose beliefs influenced his music", "Hits include 'No Woman, No Cry' and 'Three Little Birds'", "Legendary reggae icon famous for 'One Love'", "Reggae", "Easy"],
  ["Shakira", "Born in Barranquilla, Colombia", "Her songs often feature belly dancing", "Performed at the Super Bowl LIV halftime show with Jennifer Lopez", "Hits include 'Whenever, Wherever' and 'Waka Waka'", "Famous Colombian singer whose 'Hips Don\\'t Lie'", "Latin/Pop", "Easy"],
  ["Enrique Iglesias", "His father is also a legendary Spanish singer", "Often referred to as the King of Latin Pop", "Has a signature mole on his face that he later had removed", "Hits include 'Hero' and 'Bailando'", "Famous Spanish singer", "Latin/Pop", "Medium"],
  ["Ricky Martin", "Began his career at age 12 with the all-boy pop group Menudo", "His performance at the 1999 Grammy Awards is credited with starting the Latin pop explosion", "Acted in the series The Assassination of Gianni Versace", "Hits include 'She Bangs'", "Famous Puerto Rican singer of 'Livin\\' la Vida Loca'", "Latin/Pop", "Medium"],
  ["Bad Bunny", "His real name is Benito Antonio Martínez Ocasio", "Was the most streamed artist on Spotify globally for three consecutive years", "First non-English language act to win the MTV VMA for Artist of the Year", "Hits include 'Dákiti' and 'Tití Me Preguntó'", "Famous Puerto Rican reggaeton artist", "Latin/Reggaeton", "Easy"]
];

const wb = xlsx.utils.book_new();
const ws = xlsx.utils.aoa_to_sheet(data);

const wscols = [
  {wch: 25}, {wch: 40}, {wch: 40}, {wch: 40}, {wch: 40}, {wch: 40}, {wch: 15}, {wch: 10}
];
ws['!cols'] = wscols;

xlsx.utils.book_append_sheet(wb, ws, "Music");

const filepath = path.join("C:\\\\Users\\\\ysfde\\\\OneDrive\\\\Desktop", 'music_en.xlsx');

try {
  xlsx.writeFile(wb, filepath);
  console.log('Successfully created file at: ' + filepath + ' with ' + (data.length - 1) + ' artists.');
} catch (e) {
  console.error('Error saving file: ', e.message);
}
