const xlsx = require('xlsx');
const path = require('path');

const newItems = [
  // 170 Turkish Music Words - Batch 2
  
  // Klasik & Sanat (More)
  ["Muazzez Abacı", "Vurgun", "Sanat Müziği", "Assolist", "Gazinocular Kralı", "Fasıl", "Sanat", "Medium"],
  ["Kibariye", "Lafı Mı Olur", "Roman", "Kim Bilir", "Güllü", "O Ses Türkiye", "Arabesk", "Easy"],
  ["Hüner Coşkuner", "Sanat Müziği", "Gidiyor", "Makber", "Beste", "Klasik", "Sanat", "Hard"],
  ["Adnan Şenses", "Doldur Be Meyhaneci", "Neden Saçların Beyazlamış", "Roman", "Arabesk", "Taverna", "Arabesk", "Medium"],
  ["Gönül Yazar", "Taş Bebek", "Sanat Müziği", "Gazino", "Sinema", "Assolist", "Sanat", "Hard"],
  ["Erol Evgin", "İşte Öyle Bir Şey", "Sevdan Olmasa", "Söyle Canım", "Altın Duetler", "Mimar", "Pop", "Medium"],
  ["Nükhet Duru", "Melankoli", "Beni Benimle Bırak", "Mahmure", "Kanto", "Pop", "Pop", "Medium"],
  ["Zerrin Özer", "Gönül", "Kıyamam", "Paşa Gönlüm", "O Yaz", "Güçlü Ses", "Pop", "Medium"],
  ["Ajda Pekkan", "Süperstar", "Pet'r Oil", "Yakar Geçerim", "Estetik", "Eurovision", "Pop", "Easy"],
  ["Nilüfer", "Yolcu Yolunda Gerek", "Erkekler Ağlamaz", "Esmer Günler", "Kayahan", "Pop", "Pop", "Medium"],
  ["Kayahan", "Gözlerinin Hapsindeyim", "Esmer Günler", "Odalarasız", "Siyah Beyaz", "Usta", "Pop", "Medium"],
  ["Cem Adrian", "Kayıp Çocuk", "Ben Seni Çok Sevdim", "Ses Telleri", "Kül", "Alternatif", "Alternatif", "Medium"],
  ["Hayko Cepkin", "Sakin Ol Şampiyon", "Yarası Saklı", "Göz", "Rock", "Paraşüt", "Rock", "Medium"],
  ["Haluk Levent", "Ahbap", "Elfida", "Yollarda Bulurum Seni", "Anadolu Rock", "Yardım", "Rock", "Easy"],
  ["Kıraç", "Dizi Müziği", "Endamın Yeter", "Kan ve Gül", "Anadolu Rock", "Fenerbahçe", "Rock", "Medium"],
  ["Murat Göğebakan", "Ay Yüzlüm", "Vurgunum", "Yaralı", "Anadolu Rock", "Gitar", "Rock", "Hard"],
  ["Murat Kekilli", "Bu Akşam Ölürüm", "Salını Salını", "Anadolu Rock", "Çılgın", "Adana", "Rock", "Medium"],
  ["Yaşar", "Kumralım", "Kuşlar", "Esirinim", "Divane", "Pop", "Pop", "Medium"],
  ["Çelik", "Ateşteyim", "Hercai", "İzel Çelik Ercan", "Kazak", "Pop", "Pop", "Medium"],
  ["Ercan Saatçi", "İzel Çelik Ercan", "Sayesinde", "Spor Yazarı", "Koro", "Pop", "Pop", "Hard"],
  ["İzel", "Kızımız Olacaktı", "Hasretim", "İzel Çelik Ercan", "Pop", "Beste", "Pop", "Medium"],
  ["Burak Kut", "Benimle Oynama", "Bebeto", "Yaşandı Bitti", "Pop", "90lar", "Pop", "Medium"],
  ["Hakan Peker", "Karam", "Efsane", "Ateşini Yolla Bana", "Dans", "Pop", "Pop", "Medium"],
  ["Tuğba Özerk", "Lo Lo Lo", "Acı Hatıralar", "Pop", "Aşkın Nur Yengi", "İzmir", "Pop", "Hard"],
  ["Aşkın Nur Yengi", "Sevgilim", "Ayrılmam", "Yabani", "Pop", "90lar", "Pop", "Medium"],
  ["Yonca Evcimik", "Abone", "Bandıra Bandıra", "Çılgın Bediş", "Dans", "Pop", "Pop", "Medium"],
  ["Demet Sağıroğlu", "Arnavut Kaldırımı", "Kınalı Bebek", "Pop", "90lar", "Şarkıcı", "Pop", "Hard"],
  ["Grup Vitamin", "İsmail", "Ellere Var Da Bize Yok Mu", "Komik", "Parodi", "Gökhan Semiz", "Pop", "Medium"],
  ["MFÖ", "Mazhar Fuat Özkan", "Ele Güne Karşı", "Güllerin İçinden", "Ali Desidero", "Grup", "Pop", "Easy"],
  ["Mazhar Alanson", "MFÖ", "Yandım", "Ah Bu Ben", "Gora", "Şapka", "Pop", "Easy"],
  ["Özkan Uğur", "MFÖ", "Gora", "Cennet Mahallesi", "Bas Gitar", "Garavel", "Pop", "Easy"],
  ["Fuat Güner", "MFÖ", "Gitarist", "Beste", "Vokal", "Pop", "Pop", "Medium"],
  ["Barış Akarsu", "Akademi Türkiye", "Islak Islak", "Yalancı Yarim", "Amasra", "Rock", "Rock", "Easy"],
  ["Gülhan", "Gülhanın Galaksi Rehberi", "Dokun Bana", "Pop Rock", "Sunucu", "Vj", "Rock", "Hard"],
  ["Aylin Aslım", "Senin Gibi", "Ben Kalender Meşrebim", "Gülyabani", "Rock", "Elektronik", "Rock", "Medium"],
  ["Pamela", "İstanbul", "Ayrılamayız Biz", "Teoman", "Rock", "Kırmızı Saç", "Rock", "Medium"],
  ["Göksel", "Depresyondayım", "Bi Seni Konuşurum", "Günün Birinde", "Pop", "Retro", "Pop", "Medium"],
  ["Gökhan Kırdar", "Yerine Sevemem", "Kurtlar Vadisi", "Cendere", "Dizi Müziği", "Pop", "Pop", "Medium"],
  ["Toygar Işıklı", "Ezel", "Kuzey Güney", "Dizi Müziği", "Çukur", "Aşk-ı Memnu", "Pop", "Medium"],
  ["Fahir Atakoğlu", "Piyano", "Belgesel", "Müzisyen", "Beste", "Senfonik", "Klasik", "Hard"],
  ["Tuluyhan Uğurlu", "Piyano", "İstanbul Kanatlarımın Altında", "Klasik Müzik", "Güneşin Askerleri", "Beste", "Klasik", "Hard"],
  ["Fazıl Say", "Piyano", "Dünyaca Ünlü", "Besteci", "Klasik Müzik", "Kara Toprak", "Klasik", "Medium"],
  ["İdil Biret", "Piyano", "Harika Çocuk", "Klasik Müzik", "Chopin", "Dünyaca Ünlü", "Klasik", "Hard"],
  ["Suna Kan", "Keman", "Harika Çocuk", "Klasik Müzik", "Devlet Sanatçısı", "Dünyaca Ünlü", "Klasik", "Hard"],
  ["Cihat Aşkın", "Keman", "Klasik Müzik", "Virtüöz", "Devlet Sanatçısı", "Beste", "Klasik", "Hard"],
  
  // Güncel Pop ve Rap Devamı
  ["Berkay", "İnanırım", "Gel Gel", "Taburcu", "Pop", "Arda Turan", "Pop", "Medium"],
  ["Koray Avcı", "Sokak Müzisyeni", "Hoşgeldin", "Sen", "Aşk Sana Benzer", "Sakallı", "Pop", "Medium"],
  ["İlyas Yalçıntaş", "İncir", "İçimdeki Duman", "X Factor", "Pop", "Romantik", "Pop", "Medium"],
  ["Buray", "İstersen", "Sen Sevda Mısın", "Mecnun", "Kıvırcık Saç", "Pop", "Pop", "Medium"],
  ["Ersay Üner", "İki Aşık", "Tatlım Tatlım", "Besteci", "Büşra Pekin", "Demet Akalın", "Pop", "Medium"],
  ["Sinan Akçıl", "Besteci", "Şarttır", "Fark Atıyor", "Ebru Şallı", "Hande Yener", "Pop", "Medium"],
  ["Mustafa Ceceli", "Es", "Hastalıkta Sağlıkta", "Aranjör", "İlle De Aşk", "Gül Rengi", "Pop", "Easy"],
  ["Emrah", "Küçük Emrah", "Götür Beni Gittiğin Yere", "Acıların Çocuğu", "Boynu Bükükler", "Arabesk", "Arabesk", "Easy"],
  ["Mahsun Kırmızıgül", "Alem Buysa", "Yıkılmadım", "Mucize", "Yönetmen", "Arabesk", "Arabesk", "Easy"],
  ["Özcan Deniz", "Asmalı Konak", "Yalan Mı", "Dön Desem", "Sinema", "Arabesk", "Arabesk", "Easy"],
  ["Kutsi", "Sana Ne", "İlanı Aşk", "Doktorlar", "Dizi", "Pop", "Pop", "Medium"],
  ["Rafet El Roman", "Macera Dolu Amerika", "Yalancı Şahidim", "Seni Seviyorum", "Almanya", "Pop", "Pop", "Medium"],
  ["Yusuf Güney", "Aşkım Aşkım", "Heder Oldum Aşkına", "Rafet El Roman", "Kaptan", "Pop", "Pop", "Medium"],
  ["Keremcem", "Nerelere Gideyim", "Ağlayalım Beraber", "Aşk Oyunu", "Dizi Oyuncusu", "Pop", "Pop", "Medium"],
  ["Halil Sezai", "İsyan", "İncir Reçeli", "Paramparça", "Dizi Oyuncusu", "Pop", "Pop", "Medium"],
  ["Oğuzhan Uğur", "Babala", "Çok Şükür", "Pinç", "Mevzular Açık Mikrofon", "Youtube", "Pop", "Medium"],
  ["Şahin Kendirci", "Müslüm", "O Ses Çocuklar", "Adana", "Arabesk", "Sinema", "Arabesk", "Hard"],
  
  // Türkü & Halay & Yöresel
  ["İbrahim Erkal", "Canısı", "Erzurum", "Sırılsıklam", "Unutmayacağım", "Fantezi", "Arabesk", "Medium"],
  ["Zara", "Eşkıya Dünyaya Hükümdar Olmaz", "Türkü", "Sanat Müziği", "Pop", "Bülbül", "Türkü", "Medium"],
  ["Kubat", "Bugün", "Türkü", "Halk Müziği", "Emirdağ", "Sarı Gelin", "Türkü", "Medium"],
  ["Orhan Hakalmaz", "Seher Yeli", "Türkü", "Bağlama", "Halk Müziği", "İki Keklik", "Türkü", "Hard"],
  ["Yavuz Bingöl", "Sarı Gelin", "Turnalara Tutun da Gel", "Türkü", "Sinema", "Bağlama", "Türkü", "Medium"],
  ["Volkan Konak", "Kuzeyin Oğlu", "Cerrahpaşa", "Göklerde Kartal Gibi", "Karadeniz", "Trabzon", "Türkü", "Medium"],
  ["Resul Dindar", "Nayino", "Karmate", "Karadeniz", "Tulum", "Türkü", "Türkü", "Medium"],
  ["Kazım Koyuncu", "Şevval Sam", "Gülbeyaz", "Didou Nana", "Karadeniz", "Tulum", "Türkü", "Easy"],
  ["Şevval Sam", "Yasak Elma", "Gülbeyaz", "Leman Sam", "Karadeniz", "Türkü", "Pop", "Medium"],
  ["Leman Sam", "İlla", "Gül Güzeli", "Rüzgar", "Kıvırcık Saç", "Pop", "Pop", "Medium"],
  ["Candan Erçetin", "Gamsız Hayat", "Yalan", "Fransızca", "Galatasaray", "Pop", "Pop", "Medium"],
  ["Nil Karaibrahimgil", "Kek", "Pırlanta", "Organize İşler", "Reklam Müziği", "Sertab Erener", "Pop", "Medium"],
  ["Sıla", "Dan Sonra", "Sevişmeden Uyumayalım", "Vaziyetler", "Ahmet Kural", "Pop", "Pop", "Easy"],
  ["Ziynet Sali", "Rüya", "Bize Yeter", "Kıbrıs", "Pop", "Yunanistan", "Pop", "Medium"],
  ["Funda Arar", "Yak Gel", "Alagül", "Benim İçin Üzülme", "Pop", "Kıvırcık Saç", "Pop", "Medium"],
  ["Işın Karaca", "Dert Bende", "Tutunamadım", "Güçlü Ses", "Pop", "Sezen Aksu", "Pop", "Medium"],
  ["Aşkın Nur Yengi", "Ayrılmam", "Sevgilim", "Haluk Bilginer", "Pop", "90lar", "Pop", "Medium"],
  ["Reyhan Karaca", "Sevdik Sevdalandık", "Pop", "90lar", "Şarkıcı", "Kıvırcık", "Pop", "Hard"],
  ["Bendeniz", "Gitmeli", "Müjdeler Ver", "Pop", "Abajur Kız", "90lar", "Pop", "Medium"],
  ["Tayfun Duygulu", "Hadi Yine İyisin", "Pop", "90lar", "Saksafon", "Şarkıcı", "Pop", "Hard"],
  ["Ufuk Yıldırım", "Çabuk Olalım Aşkım", "Pop", "90lar", "Klavye", "Şarkıcı", "Pop", "Hard"],
  ["Ozan Doğulu", "Kenan Doğulu", "Aranjör", "DJ", "Pop", "Klavye", "Pop", "Medium"],
  ["İskender Paydaş", "Aranjör", "Kayahan", "Zamansız Şarkılar", "Davul", "Pop", "Pop", "Hard"],
  ["Erdem Kınay", "Aranjör", "Helal Etti", "Duman", "Pop", "Merve Özbey", "Pop", "Medium"],
  ["Ozan Çolakoğlu", "Gülşen", "Aranjör", "Tarkan", "Pop", "Stüdyo", "Pop", "Medium"],
  
  // Dizi & Film & Klasikler
  ["Kemal Sunal", "Hababam Sınıfı", "Şaban", "Gülüş", "Sinema", "Tosun Paşa", "Sinema", "Easy"],
  ["Cem Yılmaz", "Gora", "Stand-up", "Komedyen", "Arog", "Yahşi Batı", "Sinema", "Easy"],
  ["Melih Kibar", "Hababam Sınıfı", "Çoban Yıldızı", "Besteci", "İçimdeki Fırtına", "Piyano", "Sanat", "Hard"],
  ["Cahit Berkay", "Moğollar", "Selvi Boylum Al Yazmalım", "Dila Hanım", "Film Müziği", "Yaylı Tambur", "Rock", "Medium"],
  ["Gökhan Kırdar", "Kurtlar Vadisi", "Yerine Sevemem", "Cendere", "Film Müziği", "Elektronik", "Pop", "Medium"],
  ["Cem Karaca", "Islak Islak", "Tamirci Çırağı", "Namus Belası", "Moğollar", "Anadolu Rock", "Rock", "Easy"], // Allowed to be similar
  
  // Ek Grup ve Şarkıcılar
  ["Flört", "Cemiyette Pişiyoruz", "Lan Oğlum Böyle Olmaz", "Anadolu Rock", "Ozan Kotra", "Grup", "Rock", "Hard"],
  ["Dolu Kadehi Ters Tut", "Aldattın Mı", "Yapma N'olursun", "Bağımsız", "Alternatif", "Grup", "Alternatif", "Medium"],
  ["KÖFN", "Bi Tek Ben Anlarım", "Elektronik Pop", "Grup", "Dans", "Alternatif", "Pop", "Medium"],
  ["Ufo361", "Almanya", "Ezhel", "Trap", "Türk Asıllı", "Rap", "Rap", "Medium"],
  ["Mero", "Olabilir", "Almanya", "O Ses Türkiye", "Rap", "Trap", "Rap", "Medium"],
  ["Reynmen", "Derdim Olsun", "Ela", "Leila", "Youtuber", "Pop", "Pop", "Easy"],
  ["Enes Batur", "Youtuber", "Dolunay", "Baturay", "Sinema", "Antalya", "Pop", "Easy"],
  ["Ece Mumay", "Galaksi", "Peri", "Pop", "Youtube", "Şarkıcı", "Pop", "Medium"],
  ["Derya Uluğ", "Okyanus", "Canavar", "Kanun", "Pop", "Asil Gök", "Pop", "Medium"],
  ["Gökçe", "Tuttu Fırlattı", "Ne Yapardım", "Pop Rock", "Balkan", "Davul", "Pop", "Medium"],
  ["Atiye", "Salla", "Soygun Var", "Ya Habibi", "Darbuka", "Pop", "Pop", "Medium"],
  ["Murat Dalkılıç", "Kasaba", "Bir Güzellik Yapsana", "Pop", "Merve Boluğur", "İzmir", "Pop", "Medium"],
  ["Fatih Ürek", "Hadi Hadi", "Yılan Dansı", "Sus", "Erzurum", "Pop", "Pop", "Medium"],
  ["Kerimcan Durmaz", "Peşimde", "Vurulduk", "Dj", "Makyaj", "Youtube", "Pop", "Medium"],
  ["Fatih Kısaparmak", "Kilim", "Türkü", "Halk Müziği", "Bağlama", "Beste", "Türkü", "Medium"],
  ["Zara", "Türkü", "Eşkıya Dünyaya", "Sanat Müziği", "Halk Müziği", "Pop", "Türkü", "Medium"],
  ["Yıldız Tezcan", "Orhan Gencebay", "Taş Plak", "Türkü", "Arabesk", "Sinema", "Türkü", "Hard"],
  ["İsmail YK", "Şappur Şuppur", "Allah Belanı Versin", "Bombabomba", "Almanya", "Pop", "Pop", "Easy"],
  ["Doğuş", "Gamsız", "Bunun Adına Yürek Derler", "Pop", "Saksı", "Yetiştirme Yurdu", "Pop", "Medium"],
  ["Ceylan", "Küçük Ceylan", "Halay", "Türkü", "Arabesk", "İbrahim Tatlıses", "Türkü", "Medium"],
  ["İzzet Yıldızhan", "Türkü", "Halay", "İbrahim Tatlıses", "Arabesk", "Diyarbakır", "Türkü", "Medium"],
  ["Mustafa Topaloğlu", "Uzaylı", "Türkü", "Oy Oy Emine", "Survivor", "Komik", "Türkü", "Medium"],
  ["Nihat Doğan", "Türkü", "Survivor", "Seda Sayan", "Koyun", "Filozof", "Türkü", "Easy"],
  ["Seda Sayan", "Kadırgalı", "Ah Geceler", "Sabah Programı", "Sunucu", "Pop", "Pop", "Easy"],
  ["Bülent Serttaş", "Aşk Bodrumda Yaşanıyor", "Türkü", "Halay", "Tenis", "Komik", "Türkü", "Medium"],
  ["Sinan Yılmaz", "Kolbastı", "Karadeniz", "Trabzon", "Oyun Havası", "Kemençe", "Türkü", "Medium"],
  ["Gültekinler", "Kolbastı", "Karadeniz", "Trabzon", "Düğün", "Kemençe", "Türkü", "Hard"],
  ["Hakan Altun", "Telefonun Başında", "Teklif Ediyorum", "Ud", "Pop", "Arabesk", "Pop", "Easy"],
  ["Cengiz Kurtoğlu", "Taverna", "Liselim", "Hain Geceler", "Duvardaki Resim", "Arabesk", "Arabesk", "Medium"],
  ["Arif Susam", "Taverna", "Nikah Masası", "Piyano", "Arabesk", "Ümit Besen", "Arabesk", "Hard"],
  ["Metin Şentürk", "Kör", "Görme Engelli", "Şarkıcı", "Ud", "Pop", "Sanat", "Easy"],
  ["Zekeriya Ünlü", "Sıra Gecesi", "Şanlıurfa", "Çiğ Köfte", "Türkü", "Halay", "Türkü", "Hard"],
  ["Kardeş Türküler", "Boğaziçi Üniversitesi", "Kürtçe", "Ermenice", "Halk Müziği", "Koro", "Türkü", "Medium"],
  ["Grup Yorum", "Cemo", "Uğurlama", "Politik", "Türkü", "Halk Cephesi", "Türkü", "Medium"],
  ["Kızılırmak", "İlkay Akkaya", "Özgün Müzik", "Türkü", "Grup", "Politik", "Türkü", "Hard"],
  ["Yeni Türkü", "Bana Bir Masal Anlat Baba", "Telli Telli", "Vira Vira", "Derya Köroğlu", "Özgün Müzik", "Pop", "Medium"],
  ["Ezginin Günlüğü", "Düşler Sokağı", "Sigaramın Dumanına Sarsam", "Ebruli", "Nadir Göktürk", "Özgün Müzik", "Pop", "Medium"],
  ["Pilli Bebek", "Behzat Ç", "Haram Geceler", "Kızıl Gerdan", "Rock Grubu", "Ankara", "Rock", "Medium"],
  ["Redd", "Boşver", "Mutlu Olmak İçin", "Rock Grubu", "Doğan Duru", "Gitar", "Rock", "Hard"],
  ["Model", "Değmesin Ellerimiz", "Pembe Mezarlık", "Fatma Turgut", "Rock Grubu", "Dağıldı", "Rock", "Medium"],
  ["Kolpa", "Böyle Ayrılık Olmaz", "Gurur Benim Neyime", "Rock Grubu", "Pop Rock", "Beste", "Rock", "Medium"],
  ["Yüksek Sadakat", "Belki Üstümüzden Bir Kuş Geçer", "Haydi Gel İçelim", "Eurovision", "Rock Grubu", "Kenan Vural", "Rock", "Medium"],
  ["Ogün Sanlısoy", "Saydım", "Pencere", "Pentagram", "Rock", "Metal", "Rock", "Medium"],
  ["Pentagram", "Metal", "Anatolia", "Bir", "Rock Grubu", "Hakan Utangaç", "Rock", "Hard"],
  ["Kurban", "Yalan", "Sarı Çizmeli Mehmet Ağa", "Deniz Yılmaz", "Rock Grubu", "Metal", "Rock", "Hard"],
  ["Çilekeş", "Y.O.K", "Siyah", "Rock Grubu", "Metal", "Görkem", "Rock", "Hard"],
  ["Vega", "Bu Sabahların Bir Anlamı Olmalı", "Elimde Değil", "Rock Grubu", "Deniz Özbey", "Elektronik", "Rock", "Medium"],
  ["Asım Can Gündüz", "Gitarist", "Awesome John", "Blues", "Rock", "Komik", "Rock", "Hard"],
  ["Gitar", "Akustik", "Klasik", "Elektro", "Bas", "Pena", "Enstrüman", "Easy"],
  ["Bateri", "Davul", "Baget", "Ritim", "Zil", "Pedal", "Enstrüman", "Easy"],
  ["Piyano", "Tuş", "Siyah Beyaz", "Kuyruklu", "Fazıl Say", "Klasik", "Enstrüman", "Easy"],
  ["Keman", "Yaylı", "Çene", "Klasik Müzik", "Suna Kan", "Arşe", "Enstrüman", "Easy"],
  ["Flüt", "Yan", "Blok", "Nefesli", "Müzik Dersi", "Okul", "Enstrüman", "Medium"],
  ["Mızıka", "Blues", "Nefesli", "Ağız", "Küçük", "Kovboy", "Enstrüman", "Medium"],
  ["Akordeon", "Körüklü", "Tuşlu", "Balkan", "Rusya", "Tango", "Enstrüman", "Medium"],
  ["Kontrbas", "Keman", "Büyük", "Caz", "Yaylı", "Ayakta", "Enstrüman", "Hard"],
  ["Çello", "Viyolonsel", "Yaylı", "Keman", "Büyük", "Apocalyptica", "Enstrüman", "Hard"],
  ["Trompet", "Nefesli", "Caz", "Sarı", "Miles Davis", "Üflemeli", "Enstrüman", "Medium"],
  ["Saksafon", "Caz", "Nefesli", "Sarı", "Blues", "Üflemeli", "Enstrüman", "Medium"],
  ["Org", "Klavye", "Elektronik", "Tuşlu", "Piyano", "Düğün", "Enstrüman", "Medium"],
  ["Arp", "Telli", "Melek", "Büyük", "Klasik Müzik", "Yunan", "Enstrüman", "Hard"],
  ["Ritim", "Tempo", "Vurmalı", "Davul", "Darbuka", "Metronom", "Terim", "Medium"],
  ["Nota", "Do Re Mi", "Müzik", "Kağıt", "Porte", "Sol Anahtarı", "Terim", "Easy"],
  ["Koro", "Şarkı", "Topluluk", "Birlikte", "Ses", "Polifonik", "Terim", "Easy"]
];

const existingFile = path.join("C:\\\\Users\\\\ysfde\\\\OneDrive\\\\Desktop", 'music_tr.xlsx');
const wb = xlsx.readFile(existingFile);
const ws = wb.Sheets["Music"];

const existingData = xlsx.utils.sheet_to_json(ws, {header: 1});
const combinedData = existingData.concat(newItems);

const newWs = xlsx.utils.aoa_to_sheet(combinedData);
newWs['!cols'] = ws['!cols'];
wb.Sheets["Music"] = newWs;

try {
  xlsx.writeFile(wb, existingFile);
  console.log('Successfully appended! Total rows: ' + combinedData.length);
} catch (e) {
  console.error(e);
}
