const fs = require('fs');

const newWords = [
  // Türkiye Süper Lig Takımları
  { word: 'Galatasaray', forbidden: ['Cimbom', 'Sarı Kırmızı', 'Aslan', 'Okan Buruk', 'Ali Sami Yen'] },
  { word: 'Fenerbahçe', forbidden: ['Sarı Lacıvert', 'Kanarya', 'Kadıköy', 'Şükrü Saracoğlu', 'İsmail Kartal'] },
  { word: 'Beşiktaş', forbidden: ['Siyah Beyaz', 'Kartal', 'Çarşı', 'Tüpraş Stadyumu', 'Dolmabahçe'] },
  { word: 'Trabzonspor', forbidden: ['Bordo Mavi', 'Fırtına', 'Karadeniz', 'Papara Park', 'Şampiyon'] },
  { word: 'Başakşehir', forbidden: ['Bozbaykuşlar', 'Fatih Terim Stadyumu', 'Turuncu Lacivert', 'Şampiyon', 'İstanbul'] },
  { word: 'Kasımpaşa', forbidden: ['Recep Tayyip Erdoğan', 'Lacivert Beyaz', 'İstanbul', 'Semt', 'Paşa'] },
  { word: 'Fatih Karagümrük', forbidden: ['Kırmızı Siyah', 'Vefa', 'İstanbul', 'Semt', 'Süleyman Hurma'] },
  { word: 'Sivasspor', forbidden: ['Yiğido', 'Kırmızı Beyaz', 'Sivas', 'Mecnun Otyakmaz', '4 Eylül'] },
  { word: 'Antalyaspor', forbidden: ['Akrep', 'Kırmızı Beyaz', 'Akdeniz', 'Corendon', 'Sergen Yalçın'] },
  { word: 'Alanyaspor', forbidden: ['Turuncu Yeşilli', 'Akdeniz', 'Oba', 'Alanya', 'Farioli'] },
  { word: 'Konyaspor', forbidden: ['Yeşil Beyaz', 'Anadolu Kartalı', 'Konya', 'Nalçacılılar', 'Mevlana'] },
  { word: 'Kayserispor', forbidden: ['Sarı Kırmızı', 'Anadolu Yıldızı', 'Kayseri', 'Kadir Has', 'Pastırma'] },
  { word: 'Gaziantep FK', forbidden: ['Kırmızı Siyah', 'Antep', 'Şahinler', 'Baklava', 'Güneydoğu'] },
  { word: 'Ankaragücü', forbidden: ['Sarı Lacivert', 'Başkent', 'Gecekondu', 'Eryaman', 'Emre Belözoğlu'] },
  { word: 'Hatayspor', forbidden: ['Bordo Beyaz', 'Antakya', 'Volkan Demirel', 'Künefe', 'Güney'] },
  { word: 'Pendikspor', forbidden: ['Kırmızı Beyaz', 'İstanbul', 'Semt', 'Pendik', 'Marmara'] },
  { word: 'İstanbulspor', forbidden: ['Sarı Siyah', 'Boğalar', 'İstanbul', 'Esenyurt', 'Büyükçekmece'] },
  { word: 'Samsunspor', forbidden: ['Kırmızı Beyaz', 'Karadeniz', 'Şimşekler', '19 Mayıs', 'Ertuğrul Sağlam'] },
  { word: 'Rizespor', forbidden: ['Mavi Yeşil', 'Atmaca', 'Karadeniz', 'Çay', 'Rize'] },
  
  // Türkiye 1. Lig ve Alt Lig Takımları
  { word: 'Göztepe', forbidden: ['Sarı Kırmızı', 'İzmir', 'Gürsel Aksel', 'Yalı', 'Körfez'] },
  { word: 'Karşıyaka', forbidden: ['Yeşil Kırmızı', 'Kaf Sin Kaf', 'İzmir', 'Göztepe', 'Körfez'] },
  { word: 'Altay', forbidden: ['Siyah Beyaz', 'Büyük Altay', 'İzmir', 'Alsancak', 'Mustafa Denizli'] },
  { word: 'Bursaspor', forbidden: ['Yeşil Beyaz', 'Timsah', 'Şampiyon', 'Bursa', 'Teksas'] },
  { word: 'Eskişehirspor', forbidden: ['Kırmızı Siyah', 'Es Es', 'Bando', 'Eskişehir', 'Anadolu'] },
  { word: 'Kocaelispor', forbidden: ['Yeşil Siyah', 'Körfez', 'İzmit', 'Hodri Meydan', 'Marmara'] },
  { word: 'Sakaryaspor', forbidden: ['Yeşil Siyah', 'Tatangalar', 'Adapazarı', 'Sakarya', 'Kocaeli'] },
  { word: 'Giresunspor', forbidden: ['Yeşil Beyaz', 'Çotanak', 'Karadeniz', 'Fındık', 'Giresun'] },
  { word: 'Denizlispor', forbidden: ['Yeşil Siyah', 'Horoz', 'Ege', 'Denizli', 'Mustafa Keçeli'] },
  { word: 'Boluspor', forbidden: ['Kırmızı Beyaz', 'Yarenler', 'Bolu', 'Köroğlu', 'Dağ'] },
  { word: 'Bandırmaspor', forbidden: ['Bordo Beyaz', 'Marmara', 'Balıkesir', 'Banvit', 'Bandırma'] },
  { word: 'Şanlıurfaspor', forbidden: ['Sarı Yeşilli', 'Urfa', 'Peygamberler', 'Güneydoğu', 'Ceylanlar'] },
  { word: 'Erzurumspor', forbidden: ['Mavi Beyaz', 'Dadaşlar', 'Doğu', 'Palandöken', 'Erzurum'] },

  // İngiltere Premier Lig Takımları
  { word: 'Arsenal', forbidden: ['Topçular', 'Londra', 'Emirates', 'Arteta', 'Kırmızı Beyaz'] },
  { word: 'Aston Villa', forbidden: ['Bordo Mavi', 'Birmingham', 'Villa Park', 'Unai Emery', 'Aslan'] },
  { word: 'Chelsea', forbidden: ['Maviler', 'Londra', 'Stamford Bridge', 'Abramovich', 'Pochettino'] },
  { word: 'Everton', forbidden: ['Maviler', 'Liverpool', 'Goodison Park', 'Toffees', 'Merseyside'] },
  { word: 'Liverpool', forbidden: ['Kırmızılar', 'Anfield', 'Klopp', 'You Never Walk Alone', 'Salah'] },
  { word: 'Manchester City', forbidden: ['Maviler', 'Guardiola', 'Etihad', 'Şampiyon', 'Haaland'] },
  { word: 'Manchester United', forbidden: ['Kırmızı Şeytanlar', 'Old Trafford', 'Ferguson', 'Ronaldo', 'Ten Hag'] },
  { word: 'Newcastle United', forbidden: ['Siyah Beyaz', 'St James Park', 'Magpies', 'Suudi Arabistan', 'Kuzey'] },
  { word: 'Tottenham Hotspur', forbidden: ['Spurs', 'Londra', 'Kuzey', 'Postecoglou', 'Kane'] },
  { word: 'West Ham United', forbidden: ['Çekiçler', 'Londra', 'Olimpiyat', 'Bordo Mavi', 'Baloncuk'] },
  { word: 'Wolverhampton', forbidden: ['Kurtlar', 'Turuncu', 'Molineux', 'Portekiz', 'Wolves'] },
  { word: 'Crystal Palace', forbidden: ['Kartallar', 'Londra', 'Selhurst Park', 'Kırmızı Laci', 'Güney'] },
  { word: 'Fulham', forbidden: ['Siyah Beyaz', 'Londra', 'Craven Cottage', 'Nehir', 'Thames'] },
  { word: 'Brighton', forbidden: ['Martılar', 'Mavi Beyaz', 'Güney', 'De Zerbi', 'Sahil'] },
  { word: 'Brentford', forbidden: ['Arılar', 'Kırmızı Beyaz', 'Londra', 'Danimarka', 'Frank'] },
  { word: 'Nottingham Forest', forbidden: ['Kırmızılar', 'Ağaç', 'Avrupa Kupası', 'City Ground', 'Nottingham'] },
  { word: 'Bournemouth', forbidden: ['Kirazlar', 'Kırmızı Siyah', 'Güney', 'Sahil', 'Vitality'] },
  { word: 'Burnley', forbidden: ['Bordo Mavi', 'Kompany', 'Turf Moor', 'Kuzey', 'Clarets'] },
  { word: 'Sheffield United', forbidden: ['Kılıçlar', 'Kırmızı Beyaz', 'Çelik', 'Bramall Lane', 'Yorkshire'] },

  // İngiltere Championship (2. Lig)
  { word: 'Leicester City', forbidden: ['Tilkiler', 'Mavi Beyaz', 'Şampiyon', 'Vardy', 'King Power'] },
  { word: 'Leeds United', forbidden: ['Beyazlar', 'Yorkshire', 'Elland Road', 'Bielsa', 'Güller'] },
  { word: 'Southampton', forbidden: ['Azizler', 'Kırmızı Beyaz', 'Güney', 'St Marys', 'Sahil'] },
  { word: 'Sunderland', forbidden: ['Kara Kediler', 'Kırmızı Beyaz', 'Kuzey', 'Stadium of Light', 'Belgesel'] },
  { word: 'Ipswich Town', forbidden: ['Mavi Beyaz', 'Traktörler', 'Doğu', 'Kieran McKenna', 'Portman Road'] },
  { word: 'Middlesbrough', forbidden: ['Kırmızılar', 'Kuzey', 'Riverside', 'Carrick', 'Boro'] },
  { word: 'West Bromwich', forbidden: ['Çizgililer', 'Mavi Beyaz', 'Birmingham', 'Hawthorns', 'Baggies'] },
  { word: 'QPR', forbidden: ['Mavi Beyaz', 'Londra', 'Loftus Road', 'Hoops', 'Queens'] },

  // İspanya La Liga
  { word: 'Real Madrid', forbidden: ['Beyazlar', 'Bernabeu', 'Kralın Takımı', 'Ancelotti', 'Şampiyonlar Ligi'] },
  { word: 'Barcelona', forbidden: ['Katalan', 'Nou Camp', 'Xavi', 'Messi', 'Bordo Mavi'] },
  { word: 'Atletico Madrid', forbidden: ['Kırmızı Beyaz', 'Simeone', 'Wanda Metropolitano', 'Yatakçılar', 'Başkent'] },
  { word: 'Sevilla', forbidden: ['Kırmızı Beyaz', 'Endülüs', 'Avrupa Ligi', 'Ramos', 'Sanchez Pizjuan'] },
  { word: 'Valencia', forbidden: ['Yarasalar', 'Mestalla', 'Beyaz Siyah', 'Doğu', 'Portakal'] },
  { word: 'Villarreal', forbidden: ['Sarı Denizaltı', 'Seramik', 'Küçük Şehir', 'Castellon', 'Sarı'] },
  { word: 'Real Betis', forbidden: ['Yeşil Beyaz', 'Endülüs', 'Sevilla', 'Benito Villamarin', 'Pellegrini'] },
  { word: 'Real Sociedad', forbidden: ['Mavi Beyaz', 'Bask', 'San Sebastian', 'Anoeta', 'Kuzey'] },
  { word: 'Athletic Bilbao', forbidden: ['Kırmızı Beyaz', 'Bask', 'San Mames', 'Sadece Bask', 'Aslanlar'] },
  { word: 'Celta Vigo', forbidden: ['Gök Mavililer', 'Galiçya', 'Balaidos', 'Iago Aspas', 'Kuzey'] },
  { word: 'Osasuna', forbidden: ['Kırmızılar', 'Pamplona', 'Navarra', 'El Sadar', 'Boğa'] },
  { word: 'Getafe', forbidden: ['Maviler', 'Madrid', 'Coliseum', 'Banliyö', 'Bordalas'] },
  { word: 'Rayo Vallecano', forbidden: ['Beyaz Kırmızı', 'Madrid', 'Semt', 'Vallecas', 'İşçi'] },
  { word: 'Mallorca', forbidden: ['Kırmızılar', 'Ada', 'Akdeniz', 'Son Moix', 'Turizm'] },
  { word: 'Las Palmas', forbidden: ['Sarı Lacivert', 'Kanarya Adaları', 'Gran Canaria', 'Ada', 'Tatil'] },
  { word: 'Girona', forbidden: ['Kırmızı Beyaz', 'Katalonya', 'City Group', 'Montilivi', 'Sürpriz'] },
  
  // İspanya 2. Lig
  { word: 'Espanyol', forbidden: ['Mavi Beyaz', 'Katalonya', 'Barselona', 'Papağanlar', 'Cornella'] },
  { word: 'Real Valladolid', forbidden: ['Mor Beyaz', 'Ronaldo', 'Jose Zorrilla', 'Kastilya', 'Pucela'] },
  { word: 'Real Zaragoza', forbidden: ['Beyaz Mavi', 'Aragon', 'La Romareda', 'Köklü', 'Zaragoza'] },
  { word: 'Levante', forbidden: ['Kurbağalar', 'Kırmızı Mavi', 'Valencia', 'Ciutat', 'Doğu'] },
  { word: 'Sporting Gijon', forbidden: ['Kırmızı Beyaz', 'Asturias', 'El Molinon', 'Kuzey', 'Quini'] },
  { word: 'Tenerife', forbidden: ['Beyaz Mavi', 'Kanarya Adaları', 'Ada', 'Heliodoro', 'Teide'] },

  // Fransa Ligue 1
  { word: 'Paris Saint-Germain', forbidden: ['Mavi Kırmızı', 'Paris', 'Mbappe', 'Katar', 'Parc des Princes'] },
  { word: 'Marseille', forbidden: ['Mavi Beyaz', 'Marsilya', 'Velodrome', 'Güney', 'Ateşli'] },
  { word: 'Lyon', forbidden: ['Kırmızı Mavi', 'Groupama', 'Juninho', 'Aulas', 'Fransa'] },
  { word: 'Monaco', forbidden: ['Kırmızı Beyaz', 'Prens', 'Monte Carlo', 'Vergisiz', 'Louis II'] },
  { word: 'Lille', forbidden: ['Kırmızı Beyaz', 'Kuzey', 'Köpekler', 'Yusuf Yazıcı', 'Şampiyon'] },
  { word: 'Lens', forbidden: ['Sarı Kırmızı', 'Kan, Altın', 'Kuzey', 'Bollaert', 'Maden'] },
  { word: 'Rennes', forbidden: ['Kırmızı Siyah', 'Breton', 'Roazhon', 'Pinault', 'Batı'] },
  { word: 'Nice', forbidden: ['Kırmızı Siyah', 'Güney', 'Riviera', 'Ineos', 'Kartallar'] },
  { word: 'Toulouse', forbidden: ['Mor Beyaz', 'Menekşeler', 'Güney', 'Data', 'Kupa'] },
  { word: 'Nantes', forbidden: ['Sarı Yeşil', 'Kanaryalar', 'Batı', 'Beaujoire', 'Kupa'] },
  { word: 'Strasbourg', forbidden: ['Mavi Beyaz', 'Alsas', 'Doğu', 'Meinau', 'Almanya'] },
  { word: 'Montpellier', forbidden: ['Lacivert Turuncu', 'Güney', 'Mosson', 'Nicollin', 'Şampiyon'] },
  
  // Fransa 2. Lig (Ligue 2)
  { word: 'Bordeaux', forbidden: ['Lacivert Beyaz', 'Şarap', 'Şato', 'Güneybatı', 'Köklü'] },
  { word: 'Saint-Etienne', forbidden: ['Yeşiller', 'Geoffroy-Guichard', 'Kupa', 'Kazan', 'Platini'] },
  { word: 'Auxerre', forbidden: ['Mavi Beyaz', 'Guy Roux', 'Abbe-Deschamps', 'Burgonya', 'Köklü'] },
  { word: 'Metz', forbidden: ['Bordo', 'Lothringen', 'Doğu', 'Ejderha', 'Saint-Symphorien'] },
  { word: 'Troyes', forbidden: ['Mavi Beyaz', 'City Group', 'Champagne', 'Aube', 'Yo-yo'] },

  // Stadyumlar
  { word: 'Camp Nou', forbidden: ['Barcelona', 'Katalonya', 'Büyük', 'İspanya', 'Messi'] },
  { word: 'Santiago Bernabeu', forbidden: ['Real Madrid', 'Başkent', 'İspanya', 'Kral', 'Yenileme'] },
  { word: 'San Siro', forbidden: ['Milano', 'Inter', 'Milan', 'Meazza', 'İtalya'] },
  { word: 'Old Trafford', forbidden: ['Manchester United', 'Düşler Tiyatrosu', 'İngiltere', 'Kırmızı', 'Sir Bobby'] },
  { word: 'Anfield', forbidden: ['Liverpool', 'You Never Walk Alone', 'Kop', 'İngiltere', 'Kırmızı'] },
  { word: 'Emirates Stadyumu', forbidden: ['Arsenal', 'Londra', 'Topçular', 'Sponsor', 'Wenger'] },
  { word: 'Stamford Bridge', forbidden: ['Chelsea', 'Londra', 'Maviler', 'Köprü', 'İngiltere'] },
  { word: 'Wembley', forbidden: ['İngiltere', 'Milli Takım', 'Kemer', 'Final', 'Londra'] },
  { word: 'Allianz Arena', forbidden: ['Bayern Münih', 'Kırmızı', 'Işık', 'Almanya', 'Münih'] },
  { word: 'Signal Iduna Park', forbidden: ['Borussia Dortmund', 'Sarı Duvar', 'Westfalen', 'Almanya', 'Büyük'] },
  { word: 'Maracana', forbidden: ['Brezilya', 'Rio', 'Efsane', 'Final', 'Pele'] },
  { word: 'La Bombonera', forbidden: ['Boca Juniors', 'Arjantin', 'Çikolata Kutusu', 'Maradona', 'Buenos Aires'] },
  { word: 'Monumental', forbidden: ['River Plate', 'Arjantin', 'Büyük', 'Buenos Aires', 'Final'] },
  { word: 'San Paolo', forbidden: ['Napoli', 'Maradona', 'İtalya', 'Güney', 'Stadyum'] },
  { word: 'Olimpiyat Stadyumu', forbidden: ['Atatürk', 'İstanbul', 'Final', 'Rüzgar', 'Uzak'] },
  { word: 'Şükrü Saracoğlu', forbidden: ['Fenerbahçe', 'Kadıköy', 'Kızıltoprak', 'Stadyum', 'İstanbul'] },
  { word: 'Ali Sami Yen', forbidden: ['Galatasaray', 'Mecidiyeköy', 'Cehennem', 'Yıkıldı', 'Stadyum'] },
  { word: 'Vodafone Park', forbidden: ['Beşiktaş', 'Tüpraş', 'Dolmabahçe', 'Boğaz', 'Ağaçlı Yol'] },
  { word: 'Wanda Metropolitano', forbidden: ['Atletico Madrid', 'İspanya', 'Yeni', 'Madrid', 'Final'] },
  { word: 'Parc des Princes', forbidden: ['PSG', 'Paris', 'Fransa', 'Prens', 'Stadyum'] },

  // Teknik Direktörler
  { word: 'Pep Guardiola', forbidden: ['Kel', 'Manchester City', 'Tiki Taka', 'Barcelona', 'Katalan'] },
  { word: 'Jurgen Klopp', forbidden: ['Gözlük', 'Gegenpressing', 'Liverpool', 'Dortmund', 'Alman'] },
  { word: 'Jose Mourinho', forbidden: ['Special One', 'Portekizli', 'Chelsea', 'Fenerbahçe', 'Real Madrid'] },
  { word: 'Carlo Ancelotti', forbidden: ['Kaş', 'Real Madrid', 'İtalyan', 'Milan', 'Şampiyonlar Ligi'] },
  { word: 'Diego Simeone', forbidden: ['Siyah Takım', 'Atletico Madrid', 'Arjantinli', 'Savunma', 'Agresif'] },
  { word: 'Mikel Arteta', forbidden: ['Arsenal', 'İspanyol', 'Guardiola', 'Genç', 'Saç'] },
  { word: 'Unai Emery', forbidden: ['Avrupa Ligi', 'Aston Villa', 'İspanyol', 'Sevilla', 'PSG'] },
  { word: 'Xabi Alonso', forbidden: ['Bayer Leverkusen', 'İspanyol', 'Yenilgisiz', 'Şampiyon', 'Eski Futbolcu'] },
  { word: 'Thomas Tuchel', forbidden: ['Alman', 'Chelsea', 'Bayern Münih', 'PSG', 'Taktik'] },
  { word: 'Antonio Conte', forbidden: ['İtalyan', 'Juventus', 'Chelsea', 'Agresif', '3-5-2'] },
  { word: 'Massimiliano Allegri', forbidden: ['İtalyan', 'Juventus', 'Savunma', 'Milan', 'Taktik'] },
  { word: 'Erik ten Hag', forbidden: ['Kel', 'Hollandalı', 'Manchester United', 'Ajax', 'Kriz'] },
  { word: 'Mauricio Pochettino', forbidden: ['Arjantinli', 'Tottenham', 'Chelsea', 'PSG', 'Genç'] },
  { word: 'Luis Enrique', forbidden: ['İspanyol', 'PSG', 'Barcelona', 'Twitch', 'Milli Takım'] },
  { word: 'Julian Nagelsmann', forbidden: ['Genç', 'Alman', 'Milli Takım', 'Bayern Münih', 'Kaykay'] },
  { word: 'Zinedine Zidane', forbidden: ['Kel', 'Fransız', 'Real Madrid', '3 Kere', 'Efsane'] },
  { word: 'Fatih Terim', forbidden: ['İmparator', 'Galatasaray', 'Milli Takım', 'İtalya', 'Adana'] },
  { word: 'Şenol Güneş', forbidden: ['Trabzon', 'Beşiktaş', 'Milli Takım', 'Kaleci', 'Dünya Üçüncüsü'] },
  { word: 'Mustafa Denizli', forbidden: ['İzmir', 'Solak', 'Şampiyon', '3 Büyükler', 'Açıklama'] },
  { word: 'İsmail Kartal', forbidden: ['Arap', 'Fenerbahçe', 'Hacı', 'Sistem', 'Balıkçı'] },
  { word: 'Okan Buruk', forbidden: ['Galatasaray', 'Başakşehir', 'Şampiyon', 'Eski Futbolcu', 'İtalya'] },
  { word: 'Sergen Yalçın', forbidden: ['Beşiktaş', 'Sol Ayak', 'At Yarışı', 'Şampiyon', 'Antalyaspor'] },
  { word: 'Aykut Kocaman', forbidden: ['Fenerbahçe', 'Konyaspor', 'Savunma', 'Matematik', 'Forvet'] },
  { word: 'Ersun Yanal', forbidden: ['Fenerbahçe', 'Trabzonspor', 'Hücum', 'Bilgisayar', 'Nisan'] },
  { word: 'Yılmaz Vural', forbidden: ['Agresif', 'Anadolu', 'Takım Değiştirme', 'Renk', 'Dayak'] },
  { word: 'Hikmet Karaman', forbidden: ['Anadolu', 'Tecrübeli', 'Röportaj', 'Almanya', 'Gözlük'] },
  
  // Futbol Terimleri & Kurallar
  { word: 'VAR Sistemi', forbidden: ['Ekran', 'Hakem', 'İptal', 'Çizgi', 'Monitör'] },
  { word: 'Ofsayt Taktiği', forbidden: ['Çizgi', 'Savunma', 'İleride Kurmak', 'Bayrak', 'Düşürmek'] },
  { word: 'Gegenpressing', forbidden: ['Klopp', 'Alman', 'Baskı', 'Topu Geri Kazanmak', 'Hücum'] },
  { word: 'Tiki Taka', forbidden: ['Guardiola', 'Barcelona', 'Pas', 'İspanya', 'Topa Sahip Olma'] },
  { word: 'Catenaccio', forbidden: ['İtalya', 'Savunma', 'Kilit', 'Beton', 'Inter'] },
  { word: 'Röveşata', forbidden: ['Ters', 'Havada', 'Vuruş', 'Gol', 'Makas'] },
  { word: 'Trivela', forbidden: ['Dış', 'Quaresma', 'Vuruş', 'Portekiz', 'Kavis'] },
  { word: 'Plase', forbidden: ['İçi', 'Köşe', 'Yumuşak', 'Vuruş', 'Falsolu'] },
  { word: 'Aşırtma', forbidden: ['Kaleci', 'Üstünden', 'Lob', 'Aşırmak', 'Vuruş'] },
  { word: 'Vole', forbidden: ['Havadan', 'Gelişine', 'Yere Düşmeden', 'Vuruş', 'Şut'] },
  { word: 'Topuk Pası', forbidden: ['Arkaya', 'Şık', 'Guti', 'Topuk', 'Top'] },
  { word: 'Asist', forbidden: ['Pas', 'Gol', 'Öncesi', 'Servis', 'Kralı'] },
  { word: 'Hattrick', forbidden: ['Üç', 'Gol', 'Aynı Maç', 'Topu Almak', 'Forvet'] },
  { word: 'Poker', forbidden: ['Dört', 'Gol', 'Aynı Maç', 'Forvet', 'Atmak'] },
  { word: 'Double', forbidden: ['İki', 'Kupa', 'Gol', 'Aynı', 'Duble'] },
  { word: 'Treble', forbidden: ['Üçleme', 'Kupa', 'Şampiyonlar Ligi', 'Lig', 'Kupa'] },
  { word: 'Box-to-Box', forbidden: ['Orta Saha', 'İki Ceza Sahası', 'Koşmak', 'Dinamik', 'Gidip Gelen'] },
  { word: 'Regista', forbidden: ['Oyun Kurucu', 'İtalya', 'Pirlo', 'Derin', 'Defans Önü'] },
  { word: 'Trequartista', forbidden: ['On Numara', 'İtalya', 'Forvet Arkası', 'Oyun Kurucu', 'Yaratıcı'] },
  { word: 'Sahte Dokuz', forbidden: ['Forvet', 'Geriye Gelen', 'Messi', 'Boşluk', 'Taktik'] },
  { word: 'Kanat Bek', forbidden: ['Defans', 'Hücum', 'Kenar', 'Çizgi', 'Wingback'] },
  { word: 'Stoper', forbidden: ['Defans', 'Ortası', 'Savunma', 'Kesici', 'Uzun'] },
  { word: 'Libero', forbidden: ['Süpürücü', 'Defans Arkası', 'Serbest', 'Beckenbauer', 'Eski'] },
  { word: 'Ön Libero', forbidden: ['Defans Önü', 'Kesici', 'Altı Numara', 'Melo', 'Orta Saha'] },
  { word: 'Falso', forbidden: ['Kavis', 'Dönerek', 'Vuruş', 'Roberto Carlos', 'Frikik'] },
  { word: 'Frikik', forbidden: ['Serbest Vuruş', 'Baraj', 'Duran Top', 'Faul', 'Hakem'] },
  { word: 'Penaltı', forbidden: ['Ceza Sahası', 'Beyaz Nokta', 'On Bir Metre', 'Faul', 'Kaleci'] },
  { word: 'Korner', forbidden: ['Köşe', 'Vuruş', 'Bayrak', 'Kafa', 'Duran Top'] },
  { word: 'Taç', forbidden: ['Çizgi', 'Elle', 'Dışarı', 'Atış', 'Oyun Alanı'] },
  { word: 'Deplasman', forbidden: ['Dış Saha', 'Rakip', 'Seyirci', 'Yolculuk', 'Avantajı'] },
  { word: 'Bonservis', forbidden: ['Transfer', 'Ücret', 'Para', 'Kulüp', 'Sözleşme'] },
  { word: 'Kiralık', forbidden: ['Geçici', 'Transfer', 'Geri Dönecek', 'Opsiyon', 'Sözleşme'] },
  { word: 'Menajer', forbidden: ['Temsilci', 'Komisyon', 'Oyuncu', 'Transfer', 'Mendes'] },
  { word: 'Scout', forbidden: ['Gözlemci', 'Keşif', 'Genç', 'Yetenek', 'İzlemek'] },
  { word: 'Derbi', forbidden: ['Aynı Şehir', 'Büyük', 'Maç', 'Rekabet', 'Heyecan'] },
  { word: 'El Clasico', forbidden: ['Real Madrid', 'Barcelona', 'İspanya', 'Derbi', 'Büyük'] },
  { word: 'Superclasico', forbidden: ['Boca', 'River', 'Arjantin', 'Derbi', 'Ateşli'] },
  { word: 'Koreografi', forbidden: ['Tribün', 'Kartal', 'Görsel', 'Şov', 'Taraftar'] },
  { word: 'Amigo', forbidden: ['Taraftar', 'Tribün Lideri', 'Bağırmak', 'Üçlü', 'Set'] },
  { word: 'Meşale', forbidden: ['Ateş', 'Kırmızı', 'Tribün', 'Duman', 'Yasak'] },
  { word: 'Pankart', forbidden: ['Yazı', 'Tribün', 'Bez', 'Mesaj', 'Taraftar'] },
  { word: 'Deplasman Otobüsü', forbidden: ['Taraftar', 'Yolculuk', 'Taş', 'Grup', 'Cam'] },
  { word: 'Holigan', forbidden: ['Kavga', 'İngiliz', 'Aşırı', 'Şiddet', 'Taraftar'] },
  { word: 'Krampon', forbidden: ['Ayakkabı', 'Çivi', 'Çim', 'Giyinmek', 'Kaymamak'] },
  { word: 'Tozluk', forbidden: ['Çorap', 'Uzun', 'Diz', 'Tekmelik', 'Giyinmek'] },
  { word: 'Tekmelik', forbidden: ['Koruma', 'Kemik', 'Tozluk İçi', 'Kaval', 'Sert'] },
  { word: 'Forma', forbidden: ['Kıyafet', 'Ter', 'Renk', 'Numara', 'Arma'] },
  { word: 'Arma', forbidden: ['Göğüs', 'Öpmek', 'Logo', 'Sembol', 'Kulüp'] },
  { word: 'Pazubent', forbidden: ['Kaptan', 'Kol', 'Takmak', 'Bant', 'Lider'] },
  { word: 'Düdük', forbidden: ['Hakem', 'Ses', 'Üflemek', 'Çalmak', 'Başlangıç'] },
  { word: 'Sarı Kart', forbidden: ['İhtar', 'Uyarı', 'Hakem', 'Cepte', 'Faul'] },
  { word: 'Kırmızı Kart', forbidden: ['Atılmak', 'İhraç', 'On Kişi', 'Hakem', 'Soyunma Odası'] },
  { word: 'Dördüncü Hakem', forbidden: ['Tabela', 'Değişiklik', 'Uzatma', 'Kenar', 'Yedek'] },
  { word: 'Gözlemci', forbidden: ['Hakem', 'Not', 'Tribün', 'TFF', 'Rapor'] },
  { word: 'Yayıncı Kuruluş', forbidden: ['Kamera', 'Televizyon', 'Maç', 'Spiker', 'Bein'] },
  { word: 'Spiker', forbidden: ['Anlatmak', 'Maç', 'Ses', 'Mikrofon', 'Yorumcu'] },
  { word: 'Yorumcu', forbidden: ['Maç', 'Eski Futbolcu', 'Değerlendirme', 'Televizyon', 'Analiz'] },
  { word: 'Basın Toplantısı', forbidden: ['Gazeteci', 'Soru', 'Maç Sonu', 'Teknik Direktör', 'Mikrofon'] },
  { word: 'Karma Alan (Mixed Zone)', forbidden: ['Gazeteci', 'Röportaj', 'Futbolcu', 'Geçiş', 'Stadyum'] },
  { word: 'Yedek Kulübesi', forbidden: ['Oturmak', 'Oyuncu Değişikliği', 'Teknik Direktör', 'Kenar', 'Isınmak'] },
  { word: 'Isınmak', forbidden: ['Maç Öncesi', 'Hareket', 'Koşmak', 'Sakatlık', 'Yedek'] },
  { word: 'Sakatlık', forbidden: ['Acı', 'Doktor', 'Sedye', 'Oyundan Çıkmak', 'Yırtık'] },
  { word: 'Sedye', forbidden: ['Sakatlık', 'Taşımak', 'Doktor', 'Saha Dışı', 'Yatmak'] },
  { word: 'Tedavi', forbidden: ['Doktor', 'Sprey', 'Buz', 'Saha İçi', 'Sağlık'] },
  { word: 'Devre Arası', forbidden: ['Mola', 'On Beş Dakika', 'Soyunma Odası', 'Dinlenmek', 'Taktik'] },
  { word: 'Uzatma Dakikaları', forbidden: ['Maç Sonu', 'Artı', 'Tabela', 'İlave', 'Ekstra'] },
  { word: 'Altın Gol', forbidden: ['Eski Kural', 'Uzatma', 'Atan Kazanır', 'Biter', 'İlhan Mansız'] },
  { word: 'Gümüş Gol', forbidden: ['Eski Kural', 'Uzatma', 'Devre Sonu', 'Biter', 'Avrupa Şampiyonası'] },
  { word: 'Penaltı Atışları', forbidden: ['Beraberlik', 'Eleme', 'Heyecan', 'Kaleci', 'Nokta'] },
  { word: 'Averaj', forbidden: ['Puan Eşitliği', 'Gol Farkı', 'İkili', 'Genel', 'Sıralama'] },
  { word: 'Şampiyonluk', forbidden: ['Kupa', 'Birinci', 'Madalya', 'Kutlama', 'Tur'] },
  { word: 'Küme Düşme', forbidden: ['Alt Lig', 'Sonuncu', 'Gözyaşı', 'Matematiksel', 'Veda'] },
  { word: 'Play-off', forbidden: ['Eleme', 'Yükselme', 'Ekstra', 'Maç', 'Final'] },
  { word: 'Fikstür', forbidden: ['Maç Programı', 'Çekim', 'Hafta', 'Takvim', 'Kura'] },
  { word: 'Kura Çekimi', forbidden: ['Top', 'Kase', 'Eşleşme', 'Şampiyonlar Ligi', 'Rakip'] },
  { word: 'Sözleşme', forbidden: ['İmza', 'Kağıt', 'Süre', 'Para', 'Fesih'] },
  { word: 'Serbest Kalma Bedeli', forbidden: ['Para', 'Bonservis', 'Sözleşme', 'Ödemek', 'Madde'] },
  { word: 'Altyapı', forbidden: ['Genç', 'Akademi', 'A Takım', 'U-19', 'Yetişmek'] },
  { word: 'A Takım', forbidden: ['As Kadro', 'Profesyonel', 'Altyapı', 'Çıkmak', 'Oynamak'] },
  { word: 'Jübile', forbidden: ['Veda', 'Bırakmak', 'Son Maç', 'Emekli', 'Futbolu'] }
];

const existing = JSON.parse(fs.readFileSync('./assets/data/words.json', 'utf8'));

// Filter out duplicates
const currentWords = new Set(existing.map(w => w.word));
const uniqueNewWords = newWords.filter(w => !currentWords.has(w.word));

const finalWords = [...existing, ...uniqueNewWords];

fs.writeFileSync('./assets/data/words.json', JSON.stringify(finalWords, null, 2));

console.log(`Added ${uniqueNewWords.length} new words. Total is now ${finalWords.length}`);
